### ISSUE TITLE
Use of deprecated: from IPython import display

### ISSUE THREAD

**Issue by jfkw** [bloomberg/bqplot#10]
Examples and source use:
```
from IPython.display import display
```
Jupyter 4.0.3 warning: You should import from ipykernel or jupyter_client instead

I don't yet know the equivalent to the deprecated IPython.display, but as I am having no success yet displaying bqplot inline images, executed cell index remains at [*] with no other information), it seemed worth mentioning.

**Comment by jasongrout** [comment]
Just checking, did you install the javascript into the notebook?  `python -m bqplot.install --user`?

**Comment by jasongrout** [comment]
Also, I'm not getting a warning from importing display.  Can you try making a new notebook and doing `from IPython.display import display`?

**Comment by SylvainCorlay** [comment]
@jfkw closing this issue since you confirmed it worked in #11 .
