### ISSUE TITLE
MarketMap ignores font_style on object creation

### ISSUE THREAD

**Issue by acelere** [bloomberg/bqplot#1010]
**Description**
When creating a MarketMap object, setting `font_style={'font-size':16px', 'fill':'white'}` does not have any effect. This is a regression since it used to work (see expected behavior below)

**To Reproduce**
Running slightly modified example code from [MM_examples_page](https://github.com/bloomberg/bqplot/blob/master/examples/Marks/Object%20Model/Market%20Map.ipynb) 
```
import pandas as pd
from bqplot import ColorScale, ColorAxis, DateScale, LinearScale, Axis, Lines, Figure
from ipywidgets import Label, VBox, Layout
from bqplot.market_map import MarketMap

data = pd.read_csv('country_codes.csv', index_col=[0])
country_codes = data.index.values
country_names = data['Name']

market_map = MarketMap(names=country_codes,      
                       # basic data which needs to set for each map
                       ref_data=data,            
                       # Data frame which can be used for different properties of the map
                       # Axis and scale for color data
                       tooltip_fields=['Name'],
                       layout=Layout(width='800px', height='600px'),
                      font_style = {'font-size': '16px', 'fill':'white'})

market_map
```
![current_behaviour](https://user-images.githubusercontent.com/12059585/72351999-777bcc00-36af-11ea-8d14-0092cf912526.PNG)

pip freeze for this configuration

pip freeze
alembic==1.3.2
async-generator==1.10
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
bqplot==0.12.2
certifi==2019.11.28
certipy==0.1.3
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
cvxpy==1.0.25
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
dill==0.3.1.1
ecos==2.0.7.post1
entrypoints==0.3
future==0.18.2
h5py==2.10.0
idna==2.8
importlib-metadata==1.3.0
ipydatawidgets==4.0.1
ipykernel==5.1.3
ipyparallel==6.2.4
ipython==7.11.1
ipython-genutils==0.2.0
ipyvolume==0.5.2
ipywebrtc==0.5.0
ipywidgets==7.5.1
jedi==0.15.2
Jinja2==2.10.3
json5==0.8.5
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterhub==1.0.0
jupyterlab==1.2.4
jupyterlab-server==1.0.6
jupytext==1.3.1
kiwisolver==1.1.0
lxml==4.4.2
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.2
metakernel==0.24.3
mistune==0.8.4
more-itertools==8.0.2
mpmath==1.1.0
multiprocess==0.70.9
nbconvert==5.6.1
nbformat==5.0.3
notebook==6.0.2
numpy==1.18.1
oauthlib==3.1.0
octave-kernel==0.31.0
osqp==0.6.1
pamela==1.0.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.2
pexpect==4.7.0
pickleshare==0.7.5
Pillow==7.0.0
portalocker==1.5.2
prometheus-client==0.7.1
prompt-toolkit==3.0.2
ptyprocess==0.6.0
pycparser==2.19
Pygments==2.5.2
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.6
python-dateutil==2.8.1
python-editor==1.0.4
pythreejs==2.1.1
pytz==2019.3
PyYAML==5.3
pyzmq==18.1.1
requests==2.22.0
scikit-aero==0.1
scipy==1.4.1
scs==2.1.1.post2
Send2Trash==1.5.0
six==1.13.0
SQLAlchemy==1.3.12
sympy==1.5.1
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
traittypes==0.2.1
urllib3==1.25.7
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
xlrd==1.2.0
zipp==0.6.0

**Expected behavior**
When creating the market map as per above code, the font should be white and 16px.
*note*: if changing this attribute AFTER the market map is displayed WORKS.
![expected_behaviour](https://user-images.githubusercontent.com/12059585/72351771-f7556680-36ae-11ea-96f3-96c8ebbd03e8.PNG)

`pip freeze` for known configuration that works:

 pip freeze
alembic==1.1.0
asn1crypto==0.24.0
async-generator==1.10
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
bqplot==0.11.7
certifi==2019.6.16
certipy==0.1.3
cffi==1.12.3
chardet==3.0.4
cryptography==2.7
cvxpy==1.0.25
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
dill==0.3.0
ecos==2.0.7.post1
entrypoints==0.3
future==0.17.1
h5py==2.10.0
idna==2.8
ipydatawidgets==4.0.1
ipykernel==5.1.2
ipyparallel==6.2.4
ipython==7.8.0
ipython-genutils==0.2.0
ipyvolume==0.5.2
ipywebrtc==0.5.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.1
json5==0.8.5
jsonschema==3.0.2
jupyter-client==5.3.1
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.5.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterhub==1.0.0
jupyterlab==1.1.1
jupyterlab-server==1.0.6
jupytext==1.2.3
kiwisolver==1.1.0
lxml==4.4.1
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
metakernel==0.24.2
mistune==0.8.4
mpmath==1.1.0
multiprocess==0.70.8
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
numpy==1.17.1
oauthlib==3.1.0
octave-kernel==0.31.0
osqp==0.6.1
pamela==1.0.0
pandas==0.25.1
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pycparser==2.19
Pygments==2.4.2
pyOpenSSL==19.0.0
pyparsing==2.4.2
pyrsistent==0.15.4
python-dateutil==2.8.0
python-editor==1.0.4
pythreejs==2.1.1
pytz==2019.2
PyYAML==5.1.2
pyzmq==18.1.0
requests==2.22.0
scikit-aero==0.1
scipy==1.3.1
scs==2.1.1.post2
Send2Trash==1.5.0
six==1.12.0
SQLAlchemy==1.3.8
sympy==1.4
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.2
traittypes==0.2.1
urllib3==1.25.3
wcwidth==0.1.7
webencodings==0.5.1

**Screenshots**
This is the current behaviour:

**Environment**
 - Ubuntu Linux 18.04 for the Juptyerhub side
-  Windows 10 for the browser side
 - Browser Chrome

**Additional context**
Both configurations were tested on Jupyterhub spawned containers

**Comment by martinRenou** [comment]
Thanks for opening this issue. I opened a PR that should fix it in the next release.
