### ISSUE TITLE
Multi Selector

### ISSUE THREAD

**Issue by daviddaileo** [bloomberg/bqplot#118]
I have a question regarding the Multi Selector elaborated [here](https://github.com/bloomberg/bqplot/blob/master/examples/Interaction%20Layer.ipynb).

What do you do to multi-select? I use mouse to select an interval but when I select again, only the first the interval is updated. How can I select a new interval?

Thanks

**Comment by ssunkara1** [comment]
Hi David,

Thanks for finding out a bug in the `MultiSelector` which we have fixed now. Regarding the usage details, we are adding it to the example notebook. If you want to use it in the mean while, they are as follows.

<b>Usage of MultiSelector:</b>¶
MultiSelector allows us to have multiple BrushSelectors on the same figure. This is useful for selecting several separate intervals at the same time. The usage details are as stated below.
<b>Startup:</b>
On startup, MultiSelector is the same as a BrushSelector. We can select an interval by click and drag. Once we have a the selector on the UI, we can move it by dragging the selector and reset the selection by clicking anywhere on the Figure outside the selector. 
<b>Adding a brush:</b>
To create a second Brush, click anywhere on the Figure while holding down the Ctrl (Windows) or Cmd (OS X) key. Now, we can click and drag to select an interval using the second selector. 
<b>State of the selector:</b>
At any point of time, there is at most one active BrushSelector. This is indicated by the Green border of the selector. All the inactive selectors have a Red border. The active selector behaves exactly like a normal BrushSelector.
<b>Selecting an inactive brush:</b>
To select an inactive Brush already present on the screen, click anywhere on the Figure while holding down the Shift key. Now, you can click on any existing selector to make it the active selector.
<b>Clearing all selectors:</b>
To clear all the selectors, click anywhere on the Figure while holding down the Shift + Alt + Ctrl/Cmd keys. This returns you to the startup state.
<b>Selected Values:</b>
The selected attribute of the MultiSelector is a dictionary with keys as the names of the selector and values as the selected attribute of the respective selector.

Let me know if anything is not clear. 

Thanks,
Srinivas

**Comment by daviddaileo** [comment]
Thank you Srinivas for your response.
I upgrade bqplot, `pip install --upgrade bqplot`. And then ```import bqplot``` again. I still can not multi-select. Let me know if I missed something basic here. Thanks.

**Comment by SylvainCorlay** [comment]
@daviddaileo I have not released a new version of bqplot with this fix quite yet. The next version is a major release and I will probably make a *beta* today or tomorrow. (PS: it will require ipywidgets 5beta, hence it is a significant update....)

**Comment by daviddaileo** [comment]
I look forward to it!
