### ISSUE TITLE
observe, method inherited from traitlets

### ISSUE THREAD

**Issue by daviddaileo** [bloomberg/bqplot#120]
I am playing with the [example](https://github.com/bloomberg/bqplot/blob/master/examples/Interaction%20Layer.ipynb). After running,
```python
intsel.on_trait_change(interval_change_callback, name='selected')
```
it says
```python
/home/cloud-user/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:8:
 DeprecationWarning: on_trait_change is deprecated: use observe instead
```
So I tried to use,
```python
intsel.observe(interval_change_callback, names='selected')
```
The error goes,
```python
TypeError: interval_change_callback() missing 1 required positional argument: 'value'
```
What arguments should be put in the handler `interval_change_callback()`?

**Comment by rmenegaux** [comment]
The handler has a single argument, a dictionary.

This is the `observe.__doc__`:

        Setup a handler to be called when a trait changes.

        This is used to setup dynamic notifications of trait changes.

        Parameters
        ----------
        handler : callable
            A callable that is called when a trait changes. Its
            signature should be ``handler(change)``, where ``change```is a
            dictionary. The change dictionary at least holds a 'type' key.
            * ``type``: the type of notification.
            Other keys may be passed depending on the value of 'type'. In the
            case where type is 'change', we also have the following keys:
            * ``owner`` : the HasTraits instance
            * ``old`` : the old value of the modified trait attribute
            * ``new`` : the new value of the modified trait attribute
            * ``name`` : the name of the modified trait attribute.
        names : list, str, All
            If names is All, the handler will apply to all traits.  If a list
            of str, handler will apply to all names in the list.  If a
            str, the handler will apply just to that name.
        type : str, All (default: 'change')
            The type of notification to filter by. If equal to All, then all
            notifications are passed to the observe handler.`

You can find more info in the ipywidgets examples, in `Widget Events.ipynb`

**Comment by daviddaileo** [comment]
Thank you. Got it.
