### ISSUE TITLE
PanZoom

### ISSUE THREAD

**Issue by daviddaileo** [bloomberg/bqplot#121]
When you use PanZoom as interaction, by rolling the scroll wheel in your mouse, you can zoom in or out from your plot. Is there a way to zoom in or out along only one direction instead of along both x and y at the same time? Thanks.

**Comment by rmenegaux** [comment]
Yes, you pass the scales along which you want to pan and zoom, so if you want to do so along only one direction, say x, then pass only your x-scale to the `PanZoom`:
`PanZoom(scales={'x': [my_x_scale]})`

**Comment by daviddaileo** [comment]
Great. That's cool. It will be perfect if you don't need to build three `bqplot.interacts.PanZoom` to zoom around. But it's good enough.

**Comment by SylvainCorlay** [comment]
The pyplot API gives you a toolbar with a panzoom button out the box.

You can also instantiate a Toolbar widget that has this button by default.
```
tb = Toolbar(figure=fig)
display(tb)
```

**Comment by SylvainCorlay** [comment]
The toolbar also has a "save as png" button and will have a svg dropdown soon.

**Comment by daviddaileo** [comment]
Thanks! Toolbar is useful too. But still can not zoom along one direction.

**Comment by dmadeka** [comment]
@daviddaileo Hi David, is this issue sorted out?

**Comment by daviddaileo** [comment]
It is. Thank you..
