### ISSUE TITLE
GridHeatMap

### ISSUE THREAD

**Issue by daviddaileo** [bloomberg/bqplot#122]
I am experimenting this [GridHeatMap](https://github.com/bloomberg/bqplot/blob/master/examples/GridHeatMap.ipynb). I wonder there is a way of changing the colorscale through `ColorScale(scheme='something')` so that the heat map gives red to large values and blue to small values. The default one gives green to large values and red to small values. What's more, how to display the heat map legend so that it's easier for people to tell approximately the numbers from the colors.

**Comment by dmadeka** [comment]
Hi @daviddaileo , The ColorScale accepts any scheme from the ColorBrewer website (http://colorbrewer2.org/). Alternatively, you can specify a list of colors in the following way:

`ColorScale(colors=['Blue', 'Red'])`

The color scale will linearly interpolate between the two colors.

**Comment by daviddaileo** [comment]
The interpolated colormap from blue to red is not exactly what I desire. Is there a way of implementing 
[jet colormap](http://matplotlib.org/examples/color/colormaps_reference.html), which is not sequential?

Plus, can we show the color bar somehow?

**Comment by dmadeka** [comment]
The JetColorMap is available yet, though we could probably import `matplotlib` color maps pretty easily. 

We can show the ColorBar, please look at the [Color Axis Section of the this example](https://github.com/bloomberg/bqplot/blob/master/examples/Axis%20Properties.ipynb).

Thanks!
