### ISSUE TITLE
trying to adapt to bqplot 0.6.1

### ISSUE THREAD

**Issue by stonebig** [bloomberg/bqplot#128]
![bqplot06](https://cloud.githubusercontent.com/assets/4312421/14823304/6a9da780-0bd2-11e6-8bee-99eddc32baa5.GIF)
hi,

I have a few issues trying to adapt to bqplot 0.6.1. at instalaltion time, I get a:
````
jupyter.exe nbextension enable --py bqplot
Enabling notebook extension bqplot/extension...
      - Validating: ok
````
at run time I get;
````
[NotebookApp] server_extensions is deprecated, use nbserver_extensions
D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.3\python-3.4.4.amd64\lib\site-packages\widgetsnbextension\__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[INotebookApp] Loading IPython parallel extension
[NotebookApp] Serving notebooks from local directory: D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.3\notebooks
...
...

[NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160426170626 (::1) 33.00ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3
[IPKernelApp] WARNING | Widget Javascript not detected.  It may not be installed properly.
````
I have Jupyter Notebook 4.2.0. What did I miss ?

widgetsnbextension is supposed there. maybe there is an additional step ?

pip list: adodbapi (2.6.0.7)
alabaster (0.7.7)
astroid (1.4.5)
astroML (0.3)
Babel (2.3.2)
backports-abc (0.4)
backports.shutil-get-terminal-size (1.0.0)
baresql (0.7.3)
bcolz (1.0.0)
beautifulsoup4 (4.4.1)
blaze (0.10.0)
blosc (1.3.2)
bloscpack (0.9.0)
bokeh (0.11.1)
Bottleneck (1.0.0)
bqplot (0.6.1)
brewer2mpl (1.4.1)
castra (0.1.7)
certifi (2016.2.28)
cffi (1.6.0)
click (6.6)
cloudpickle (0.2.1)
colorama (0.3.7)
cvxopt (1.1.7)
cx-Freeze (4.3.4)
cycler (0.10.0)
cyordereddict (1.0.0)
Cython (0.24)
cytoolz (0.7.5)
dask (0.8.2)
datashape (0.5.2)
db.py (0.4.4)
decorator (4.0.7)
dill (0.2.5)
docopt (0.6.2)
docrepr (0.1.0)
docutils (0.12)
emcee (2.1.0)
entrypoints (0.2.1)
Flask (0.10.1)
Flask-Cors (2.1.2)
formlayout (1.1.0)
geopy (1.11.0)
greenlet (0.4.9)
guidata (1.7.5)
guiqwt (3.0.2)
h5py (2.6.0)
holoviews (1.4.3)
html5lib (0.9999999)
husl (4.0.3)
idlex (1.13)
imagesize (0.7.1)
ipykernel (4.3.1)
ipyparallel (5.0.1)
ipython (4.2.0)
ipython-genutils (0.1.0)
ipython-sql (0.3.7.1)
ipywidgets (5.0.0)
itsdangerous (0.24)
jedi (0.9.0)
Jinja2 (2.8)
joblib (0.9.4)
jsonschema (2.5.1)
julia (0.1.1.8)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
Keras (1.0.1)
Lasagne (0.2.dev1)
lazy-object-proxy (1.2.2)
llvmlite (0.10.0)
lmfit (0.9.3)
locket (0.2.0)
lxml (3.6.0)
Markdown (2.6.6)
MarkupSafe (0.23)
matplotlib (1.5.1)
mingwpy (0.1.0b3)
mistune (0.7.2)
mkl-service (1.1.2)
mpld3 (0.2)
mpmath (0.19)
multipledispatch (0.4.8)
mysql-connector-python (2.0.4)
nbconvert (4.2.0)
nbformat (4.0.1)
netCDF4 (1.2.4)
networkx (1.11)
nltk (3.2.1)
nose (1.3.7)
notebook (4.2.0)
numba (0.25.0)
numexpr (2.5.2)
numpy (1.10.4)
numpydoc (0.6.0)
oct2py (3.5.3)
odo (0.5.0)
pandas (0.18.0)
pandas-datareader (0.2.0)
param (1.3.2)
partd (0.3.2)
patsy (0.4.1)
pep8 (1.7.0)
pg8000 (1.10.5)
pickleshare (0.7.2)
Pillow (3.2.0)
pip (8.1.1)
pkginfo (1.2.1)
prettytable (0.7.2)
prompt-toolkit (0.60)
psutil (4.1.0)
ptpython (0.32)
PuLP (1.6.1)
py (1.4.31)
PyAudio (0.2.9)
pybars3 (0.9.1)
pycparser (2.14)
pyflakes (1.1.0)
Pygments (2.1.3)
pylint (1.5.5)
pymc (2.3.6)
pymc3 (3.0)
PyMeta3 (0.5.1)
pymongo (3.2.2)
pyodbc (3.0.10)
PyOpenGL (3.1.1)
pyparsing (2.1.0)
pyqtgraph (0.9.10)
pyreadline (2.1)
pyserial (3.0.1)
pystache (0.5.4)
pytest (2.9.1)
python-dateutil (2.5.3)
python-hdf4 (0.9)
pythonnet (2.1.0)
PythonQwt (0.5.5)
pytz (2016.4)
pywin32 (220)
PyYAML (3.11)
pyzmq (15.2.0)
QtAwesome (0.3.3)
qtconsole (4.2.1)
QtPy (1.0.1)
redis (2.10.5)
reportlab (3.3.0)
requests (2.9.1)
requests-toolbelt (0.6.0)
rope-py3k (0.9.4.post1)
rpy2 (2.7.8)
Rx (1.2.6)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scikit-neuralnetwork (0.7)
scilab2py (0.6)
scipy (0.17.0)
seaborn (0.7.0)
setuptools (20.9.0)
simplegeneric (0.8.1)
simplejson (3.8.2)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.4.1)
sphinx-rtd-theme (0.1.9)
spyder (3.0.0.dev0)
SQLAlchemy (1.0.12)
sqlite-bro (0.8.11)
sqlparse (0.1.19)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
Theano (0.8.2)
toolz (0.7.4)
tornado (4.3)
traitlets (4.2.1)
twine (1.6.5)
twitter (1.17.1)
wcwidth (0.1.6)
Werkzeug (0.11.9)
wheel (0.29.0)
widgetsnbextension (1.0.0)
winpython (1.5.20160402)
wordcloud (1.2.1)
wrapt (1.10.8)
xarray (0.7.2)
xlrd (0.9.4)
XlsxWriter (0.8.5)

**Comment by stonebig** [comment]
ok, i missed the installation step `jupyter nbextension enable --py widgetsnbextension`

**Comment by SylvainCorlay** [comment]
Ah, I was just typing this! You beat me to it :)

**Comment by stonebig** [comment]
now i get the graphic, but another error at the bottom. not sure what it is about.
![bqplot06b](https://cloud.githubusercontent.com/assets/4312421/14824040/cedd3358-0bd4-11e6-9679-f3448e962772.GIF)

**Comment by SylvainCorlay** [comment]
I have seen this from time to time and suspect a timeout...

**Comment by stonebig** [comment]
other remark:
- restart & run all give me an empty drawing,
- restart & clear output, then restart & run all put me back in correct state.

==> shouldn't there be a "restart & clear output & run all" option, in this new widgets-full  world ?

**Comment by stonebig** [comment]
and there is now this mysterious "Widgets" menu. do you know where I could read/watch some explanations about it ?

**Comment by SylvainCorlay** [comment]
@stonebig regarding the widgets menu, are three things
- **Save notebook with snapshots** will save the notebook file and replace the rendered widgets with a png snapshot of whatever they look like at this moment. The point is to have widgets rendered on Github as static images.
- **Download widget state** returns a json blob which is the state of the entire widget manager. It is useful to create static webpages embedding jupyter interactive widgets.
- **Embed widgets** gives you a code snippet that you can paste in any html file to display the widgets inline.

*The widget JavaScript not detected* issue that you are seeing is more of an upstream *ipywidgets* issue. Quick question: do you have other versions of ipywidgets installed (specifically dev versions)?

**Comment by stonebig** [comment]
hi @SylvainCorlay ,

I'm probably doing ipywidget things without knowing its ipywidget things. I have bokeh,

Holoviews,matplotlib and pandas that seem to interfer with bqplot, so I suppose this is your list.

But in the pre-test of Ipywidgets 5.0, nothing but bqplot was implied.

I'll do another try after next wheel updates of ipywidget and ipython.
