### ISSUE TITLE
Cannot add points to Scatter

### ISSUE THREAD

**Issue by daviddaileo** [bloomberg/bqplot#133]
"Adding_points_to_Scatter" cell in [Scatter plot](https://github.com/bloomberg/bqplot/blob/master/examples/Scatter.ipynb) does not work for me. No new points are added by clicking.

**Comment by dmadeka** [comment]
@ssunkara1 @SylvainCorlay This seems to be a call to the deprecated `enable_add`.  Move and delete remain under the old `enable` framework, but add has been moved to the new way of processing interactions. 

@daviddaileo I will open a PR for this. However, if a quick fix is needed, change

```python

scatter2.enable_add = True
```
to
```python
scatter2.interactions = {'click': 'add'}
```

And set it to None to remove the add ability.

```python
scatter2.interactions = {'click': None}
```
