### ISSUE TITLE
Matplotlib colormaps

### ISSUE THREAD

**Issue by dmadeka** [bloomberg/bqplot#141]
Currently we only support colorbrewer ColorMaps, when matplotlib has many more that have been updated very recently.

Although there are JS libraries that mimic this:

https://github.com/politiken-journalism/scale-color-perceptual

I guess the best way to do it would be to import `matplotlib` and do it on the Python side. Maybe we can have utils that generate the colors and feed that to a `ColorScale`.

What do you think @SylvainCorlay @ssunkara1 @jasongrout @ChakriCherukuri @rmenegaux ?

**Comment by rmenegaux** [comment]
Fixed in #605
