### ISSUE TITLE
bqplot master no longer works on Firefox 46.0.1 on OS X

### ISSUE THREAD

**Issue by izaid** [bloomberg/bqplot#149]
This is an issue with the latest master from Github. On Firefox 46.0.1 on OS X, I now get a whole lot of errors like the following when I try to run *any* plot -- totally broken.

```
Unexpected value translate(0,NaN) parsing transform attribute. index.js:1965:55
Unexpected value NaN parsing x attribute. index.js:1958:7
Unexpected value translate(0, NaN) parsing transform attribute. index.js:1958:7
Unexpected value translate(NaN,0) parsing transform attribute. index.js:1965:55
Unexpected value NaN parsing x attribute. index.js:1958:7
Unexpected value NaN parsing x2 attribute. index.js:10051:11
Unexpected value NaN parsing x attribute. index.js:10051:11
Unexpected value NaN parsing y2 attribute. index.js:10051:11
Unexpected value NaN parsing y attribute.
```

To be clear, bqplot still works fine in Chome, and it worked fine from the master from a few days ago, and the pip release still works fine. But the latest master + Firefox does not work at all.

**Comment by dmadeka** [comment]
@SylvainCorlay @jasongrout Any ideas on this?

**Comment by dmadeka** [comment]
Hi @izaid everything seems to be fine on Firefox 47.0 . Is this still an issue?
