### ISSUE TITLE
Missing a file on install

### ISSUE THREAD

**Issue by blink1073** [bloomberg/bqplot#15]
I followed the install instructions for Linux (I'm on a Mac) and tried to run the example code in the notebook, but I'm getting this error:

```
[W 15:54:49.951 NotebookApp] 404 GET /nbextensions/bqplot/components/d3/d3.js (::1) 5.70ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=python3
```

**Comment by blink1073** [comment]
It looks like you need to bower install prior to creating the tarball for PyPI.

**Comment by blink1073** [comment]
(I tried with the development version and it works)

**Comment by SylvainCorlay** [comment]
@blink1073 fixed. Just pushed 0.3.8.
