### ISSUE TITLE
wealth of nations

### ISSUE THREAD

**Issue by stonebig** [bloomberg/bqplot#151]
is the typical "d3.js" demo [wealth & health of nations through the ages](http://romsson.github.io/dragit/example/nations.html) doable with bqplot/ipywidgets thing now, without having to suffer javascript webgramming ?

**Comment by SylvainCorlay** [comment]
Yes, I have made it. I should probably add it to the examples if it is not already.

**Comment by stonebig** [comment]
Can you pinpoint me to this example ?

**Comment by dmadeka** [comment]
@SylvainCorlay Do you want one of us to get this?

**Comment by SylvainCorlay** [comment]
@dmadeka that'd be great.

**Comment by dmadeka** [comment]
@SylvainCorlay Where did you get the data from?

**Comment by stonebig** [comment]
comment on today version of .ipynb example  and bqplot 6.1:
- the bottom manual year mover is tiny (1/4th of available width)
- it would be comforatble to be able to move through year with the wheel of the mouse,
- still a nigthmare with firefox

**Comment by stonebig** [comment]
no bqplot 6.2 yet ?

**Comment by dmadeka** [comment]
@stonebig We're waiting for a set of PR's:

- [ ] Tooltip fixes @ssunkara1 
- [ ] numpy datetime fix on master @ssunkara1 
- [ ] Play Widget @SylvainCorlay

**Comment by stonebig** [comment]
small remark: bqplot 0.7.1 is a little bit de-synchronized with edge
![edges_wealth](https://cloud.githubusercontent.com/assets/4312421/16925380/37c8b488-4d24-11e6-87f7-bc8886f163b2.PNG)
