### ISSUE TITLE
wheel package format

### ISSUE THREAD

**Issue by stonebig** [bloomberg/bqplot#20]
It would be wonderfull to have this:
- available as a wheel package,
- with the  `python -m bqplot.install --user` functionality triggered automatically when you detect the ".js" stuff  is not in the right place.

**Comment by jasongrout** [comment]
I agree about the wheel package.  Is there even a way to run python code at install time with a wheel package? I thought that perhaps wheels were like conda packages, i.e., they just copied files over.

**Comment by stonebig** [comment]
By definition and voluntary design, a wheel package installation doesn't run any code.

**Comment by jasongrout** [comment]
Right, so we can't run the nb extension install step automatically.

**Comment by jasongrout** [comment]
Oh, you were talking about just checking at runtime (not install time) if the js is installed.  The problem with that is that the server (with the javascript) may be very different from the kernel (running the python).  I see this a lot, for example, with different kernels for different anaconda environments.  From the python side (i.e., the kernel), I can check to see if the current ipython has an extension with the right name, but I can't check the currently-running server.

I agree that we need to have a better packaging system.  For example, maybe the python code could tell the *browser* that it needs an nbextension such-and-such version.  The browser can then query the webserver to ask if it has the correct nbextension, and present the user with an option to install it if it doesn't.

**Comment by stonebig** [comment]
ah, I didn't think about the complex case, as I only live in the simple case.

**Comment by jasongrout** [comment]
Is there a way to add a switch to a pip install? Maybe there could be an extra switch which automatically installs the js extension in the current python?

**Comment by SylvainCorlay** [comment]
The issue is that nbextensions js dependencies have to be installed on a location found by the notebook server, which might not be known by the kernel.

**Comment by stonebig** [comment]
using winpython, I launch jupyter-notebook. In that special case, don't the kernel and the server know each other ?

**Comment by SylvainCorlay** [comment]
Sorry I was not really clear. The bqplot library is mostly a notebook extension, *i.e.* JavaScript. There are essentially two types notebook extensions

- notebook-level extensions such as a slideshow-mode button, or a hide-input button, which are language and kernel-independent.
- nbextensions that interact with kernel code, such as widgets libraries.

bqplot falls in the second category. 

What is specific about the second category is that is depends on kernel-side code, which might have different versions depending on the kernel that we are using (the version of the python-side package installed)...

Hence the ideal would be to have the js side of nbextensions that depend on the kernel be put in a per-kernel directory.

```
nbextensions/ ---- ipywidgets/ ----- kernel_id1/ ---- (ipywidgets js for kernel_id1)
               |                |
               |                `-- kernel_id2/ ---- (ipywidgets js for kernel_id2)
               |
               |-- bqplot/     ----- kernel_id1/ ---- (bqplot js for kernel_id1)
               |
               `-- slideshow/  ----- (kernel-independent js for slideshow)
```

This problem of the packaging of notebook extensions are being discussed (upstream) and we have note figured out the best way to do it. That is why we have kept the installation process as a two-step process.

**Comment by SylvainCorlay** [comment]
I will push a wheel in the next version, but the second step to install the nbextension will still be required.

**Comment by stonebig** [comment]
that will be great for my use case. thanks in advance

**Comment by stonebig** [comment]
will you do this new release before next JupyterDay NYC ?

**Comment by SylvainCorlay** [comment]
Are you in NYC?

**Comment by stonebig** [comment]
no, just hopping you would release an update for that event.

**Comment by SylvainCorlay** [comment]
I can try to get a release out. We improved a few things. However, the two-stage installation will still be required.

**Comment by stonebig** [comment]
ok, my true issue is that bqplot installs its widgets in `%APPDATA%\\Roaming\\jupyter\\nbextensions\\bqplot`, which is bad from Winpython standpoint, where this would be better under WinPython root:

curent situation is:
````
paths.jupyter_path()

['C:\\Users\\famille\\AppData\\Roaming\\jupyter',
 'D:\\WinPython\\basedir34\\build\\winpython-3.4.3.amd64\\python-3.4.3.amd64\\share\\jupyter',
 'C:\\ProgramData\\jupyter']

paths.jupyter_config_path()

['D:\\WinPython\\basedir34\\build\\winpython-3.4.3.amd64\\settings\\.jupyter',
 'D:\\WinPython\\basedir34\\build\\winpython-3.4.3.amd64\\python-3.4.3.amd64\\etc\\jupyter',
 'C:\\ProgramData\\jupyter']`

! echo  %WINPYDIR%
 D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
```

I suspect the workaround I need with your first release is to:
- set JUPYTER_RUNTIME_DIR = '%APPDATA%\\Roaming\\jupyter\runtime'
- set JUPYTER_DATA_DIR= '%WINPYDIR%\\share\\jupyter'
(as there is no `JUPYTER_NBEXTENSIONS_DIR in current Jupyter scripts, which would be a better option for me)

**Comment by stonebig** [comment]
hum, my workaround doesn't seem to work,

**Comment by stonebig** [comment]
a wheel has come to pypi !

**Comment by SylvainCorlay** [comment]
@stonebig yes I pushed it yesterday but the two-stage installation is still required.

**Comment by stonebig** [comment]
yes, but now it works (again) on my pc without bothering to install nodejs. I don't understand why I had issues a few days ago. thanks !
