### ISSUE TITLE
hline and vline don't return the Mark in 0.5.x

### ISSUE THREAD

**Issue by dmadeka** [bloomberg/bqplot#230]
When you do 

```python
mark = plt.vline(10)
mark is None
```
returns `True`

**Comment by SylvainCorlay** [comment]
I thought that I did in #221

**Comment by dmadeka** [comment]
@SylvainCorlay you're right, it's fixed on master, I meant on 0.5.x, misnamed the title

**Comment by SylvainCorlay** [comment]
yeah, we have made multiple releases since 5.x I would rather not update this branch anymore and move forward..

**Comment by SylvainCorlay** [comment]
@dmadeka how about we close the 5.x issues?
