### ISSUE TITLE
gifs for displaying the dynamic aspect of bqplot

### ISSUE THREAD

**Issue by dmadeka** [bloomberg/bqplot#261]
a simple picture won't really do it. We have to show ways in which the interactivity bolsters computation. Perhaps some useful gifs, showing the python and js interact might be nice. Or just maybe a line being updated etc?

Someone with a Mac will have to do this, @SylvainCorlay @rmenegaux ?

**Comment by dmadeka** [comment]
Should we do this in the Wiki or directly in the `README`? @rmenegaux Sylvain is on vacation, can you try it?

**Comment by SylvainCorlay** [comment]
One gif in the readme displaying an application in the spirit of ycpca (or simpler) would be a good idea.

**Comment by dmadeka** [comment]
Agreed, @rmenegaux are you going to do this?

**Comment by dmadeka** [comment]
@SylvainCorlay It seems @rmenegaux isn't on this, maybe we can start with the election gif for the README? Just before the installation?

**Comment by dmadeka** [comment]
@SylvainCorlay ping
