### ISSUE TITLE
Labels pyplot example fails to serialize dates

### ISSUE THREAD

**Issue by SylvainCorlay** [bloomberg/bqplot#263]
@dmadeka This was introduced with #217

**Comment by SylvainCorlay** [comment]
This was introduced with #217

**Comment by dmadeka** [comment]
I thought I fixed this? Maybe in 0_5 but it's an easy fix, I'll get it

----- Original Message -----
From: Sylvain Corlay <reply@reply.github.com>
To: bqplot@noreply.github.com
CC: DHRUV MADEKA, mention@noreply.github.com
At: 09-Aug-2016 08:52:01


This was introduced with #217
