### ISSUE TITLE
legend_location doesn't work.

### ISSUE THREAD

**Issue by totolipton** [bloomberg/bqplot#266]
```
fig = Figure(marks=[line], axes=[ax_x, ax_y], legend_location='bottom')
display(fig)
```

In this code, the legend_location doesn't seem to do anything.

**Comment by SylvainCorlay** [comment]
Possible values are  '[bottom|top]-[left|right]'.

**Comment by SylvainCorlay** [comment]
Thanks for the report!

**Comment by rmenegaux** [comment]
I did not run into any problem with the above code, it displays the legend at the bottom of the `Figure` as expected. What exactly is the issue here?

**Comment by totolipton** [comment]
It turns out to be a IE only issue. works in chrome.

**Comment by SylvainCorlay** [comment]
@totolipton good catch! The culprit is probably the svg css transform bugs of IE. I will push a fix for the next release next week.

**Comment by dmadeka** [comment]
@SylvainCorlay I thought so too, but in `update_legend`

```javascript
            legend_g.attr("transform", "translate(" + String(coords[0] + max_label_len * em) + " " +
                                                      String(coords[1]) + ") ");
```

**Comment by SylvainCorlay** [comment]
Yeah it is an IE11 bug with translate...

**Comment by SylvainCorlay** [comment]
hum,

**Comment by dmadeka** [comment]
I couldnt recreate this issue in IE11 on master. Can anyone else?
