### ISSUE TITLE
Axis Properties notebook has broken rendering

### ISSUE THREAD

**Issue by dmadeka** [bloomberg/bqplot#275]
For the Figure scales example

**Comment by SylvainCorlay** [comment]
I don't understand.

**Comment by dmadeka** [comment]
If you run the notebook, the Axes seem to be of variable widths at 100% zoom

**Comment by dmadeka** [comment]
Okay, so I know the problem. If you set the number of ticks and pass `tick_values` larger than the `num_ticks` then the notebook renders as such:

![image](https://cloud.githubusercontent.com/assets/7892382/18407713/0dd9f906-76e7-11e6-9fc1-53d18a8b18ac.png)
