### ISSUE TITLE
NdArray default_value does nothing

### ISSUE THREAD

**Issue by rmenegaux** [bloomberg/bqplot#290]
The `default_value` of the `NdArray` trait does not work, it is not taken into account at all. 

```python
from ipywidgets import Widget
from bqplot.traits import NdArray

class A(Widget):
    ''''''
    x = NdArray(default_value=[1, 2]).tag(sync=True, min_dim=1)
    
a = A()
```
The above code fails because of a dimension mismatch (dim < min_dim), as somehow `validate` is called with `None` as an argument.

```python
class B(Widget):
    ''''''
    x = NdArray(default_value=[1, 2]).tag(sync=True)
    
b = B()
b.x
```
returns `None`

We are looking into this with @ssunkara1

**Comment by SylvainCorlay** [comment]
The base class (Instance) does not take a default value.

Although passing `args=[default_value]` to `super.__init__` should do the job for now. Eventually we should stop inheriting from Instance.

**Comment by dmadeka** [comment]
@SylvainCorlay I thought the `Instance` `__init__` called super which should call the `TraitType` init and the **metadata that is passed should set the default_value?
