### ISSUE TITLE
Pollster Example Notebook and Python 3

### ISSUE THREAD

**Issue by SylvainCorlay** [bloomberg/bqplot#318]
- Pollster 1.4 does not support Python 3
- Pollster 1.5 does but is not properly uploaded on pypi

**Comment by dmadeka** [comment]
Looks like its fixed:

https://github.com/huffpostdata/python-pollster/issues/7

**Comment by SylvainCorlay** [comment]
We should probably require a specific version in the pip command though.

**Comment by dmadeka** [comment]
Closed by #319
