### ISSUE TITLE
Issue with multiple histograms on the same scale

### ISSUE THREAD

**Issue by ssunkara1** [bloomberg/bqplot#327]
When two histograms are on the same `sample` scale, and both are updated in quick succession, the second histogram's `sample` is not updated. Still trying to narrow down on the cause of the issue. Will update the issue with code once I narrow down the code to reproduce it consistently.

**Comment by SylvainCorlay** [comment]
Does this happen only when there is a transition?

**Comment by ssunkara1** [comment]
This is fixed in `ipywidgets` `6.0.0b1`.
