### ISSUE TITLE
Axis labels should have a rotate_angle property

### ISSUE THREAD

**Issue by dmadeka** [bloomberg/bqplot#342]
@madridnick

**Comment by madridnick** [comment]
<img width="534" alt="x_axis" src="https://cloud.githubusercontent.com/assets/6982390/19365900/b7d38eaa-9149-11e6-9f94-f92eaeeefc16.png">

**Comment by thunderbelly** [comment]
+1, its alot less usefull without

**Comment by dmadeka** [comment]
#343 starts dealing with this. The question is if we wrap text or rotate, do we do both?

**Comment by madridnick** [comment]
@dmadeka , let me know where you're at with this and I can help if needed.

Here are my thoughts:
1. Include both, wrap text and rotate
2. Not sure if this makes sense but another attribute to display only certain labels (e.g,. every other --> Jan, March, May, July, etc...)

**Comment by ruxi** [comment]
Is there a fix for this?

**Comment by dmadeka** [comment]
@ruxi, can you use my PR? This is a 1.0 goal

**Comment by ruxi** [comment]
@dmadeka Will give it a try. Is there an example of it's usage?

**Comment by rmenegaux** [comment]
This was taken care of in PR #669
