### ISSUE TITLE
bqplot hanging Jupyter notebook hard

### ISSUE THREAD

**Issue by gramster** [bloomberg/bqplot#363]
Maybe I'm doing something wrong but I'd still call this a bug for hanging cell execution in Jupyter pretty solidly (enough that doing a kernel restart from Jupyter is inadequate; I seem to have to restart Jupyter completely). I'm just trying to draw a bar chart, based off the sample in the repo. This is from a conda Python 3.5 installation (recent; I installed it fresh today from Continuum).

    from bqplot import OrdinalScale, LinearScale, Bars, Axis, Figure
    import numpy as np
    from IPython.display import display

    x_data = np.array(["Small", "Medium", "Large"], dtype=object)
    y_data = np.array([0.28, 0.26, 0.22])
    x_ord = OrdinalScale()
    y_sc = LinearScale()
    bar = Bars(x=x_data, y=y_data, scales={'x': x_ord, 'y': y_sc})
    ax_x = Axis(scale=x_ord, grid_lines='solid', label='Segment')
    ax_y = Axis(scale=y_sc, orientation='vertical', tick_format='0.2f',
            grid_lines='solid', label='%')
    Figure(marks=[bar], axes=[ax_x, ax_y], title='% By Segment',
           legend_location='bottom-right')

**Comment by SylvainCorlay** [comment]
@gramster did you enable then bqplot and ipywidgets notebook extensions?
Is there any error in the javascript console?

**Comment by gramster** [comment]
Ah, I found the problem. I had used:

    conda install bqplot

instead of:

    conda install -c conda-forge bqplot

**Comment by gramster** [comment]
BTW should Figure be able to work with ipywidgets interactive? This just draws a little [x] in the output:

    def plot():
        x_data = np.array(["Small", "Medium", "Large"], dtype=object)
        y_data = np.array([0.28, 0.26, 0.22])
        x_ord = OrdinalScale()
        y_sc = LinearScale()
        bar = Bars(x=x_data, y=y_data, scales={'x': x_ord, 'y': y_sc})
        ax_x = Axis(scale=x_ord, grid_lines='solid', label='Segment')
        ax_y = Axis(scale=y_sc, orientation='vertical', tick_format='0.2f',
                    grid_lines='solid', label='%')
        Figure(marks=[bar], axes=[ax_x, ax_y], title='% By Segment',
               legend_location='bottom-right')

    display(interactive(plot))

**Comment by SylvainCorlay** [comment]
`Figure` is the figure instance. If you display it in `plot`, you should see something.


Although, what I recommend is creating the figure and axes externally and only change data attributes of marks in the function passed to `interactive`...

**Comment by gramster** [comment]
Thanks, that's helpful. Got things working this way.
