### ISSUE TITLE
Having svg as top-level Figure element is problematic

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#368]
Since we now use phosphor-based widgets, and phosphor uses the classList attribute a lot, and IE 11 (apparently) doesn't support classList for SVG elements (http://caniuse.com/#feat=classlist), we have a problem having a phosphor widget controlling an svg element (like Figure.pWidget controls Figure.el in bqplot figures).

Options include:
1. Ignore IE 11, and consider it broken.
2. Add a polyfill for IE 11 (for example, a quick search turns up https://github.com/eligrey/classList.js/, which seems to maybe work for svg?)
3. Rewrite bqplot to not have a phosphor widget with an svg node

Thoughts?

**Comment by SylvainCorlay** [comment]
We should move down the svg in the DOM and have the top-most element in bqplot be a div.

There are other benefits to this:

1. The toolbar should be a child widget to the figure. In doing so, the toolbar view will have a reference to the figure view, and the toolbar save button will be able to only save the current view, and not all the views of a given model...

2. We will be about to do other strategies for zoom that include operations on ranges...

3. We will be able to add canvas layers outside of the svg.

**Comment by jasongrout** [comment]
I was afraid you were going to pick the option that entailed the most work! :)

**Comment by ssunkara1** [comment]
I think we can close this as we changed the top level element to a div.

**Comment by jasongrout** [comment]
Yep, thanks.
