### ISSUE TITLE
Scatter example 'unhovered' style not applied first

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#378]
In scatter plot mark example, the “Adding tooltip and custom hover style” example - the initial drawing has opacity 1, but after a single hover, opacity goes to the unhovered style of opacity 0.5.

**Comment by ssunkara1** [comment]
This is not a bug. When we do not hover on anything, both `hovered_style` and `unhovered_style` should not apply. Just like, when `selected` is `None`, which means we are not even trying to select, `unselected_style` is not applied.

**Comment by jasongrout** [comment]
So the opacity should go back to 1 after I stop hovering?

**Comment by ssunkara1** [comment]
I would have expected it to. But it doesn't as of now. So we'll keep this open till that is fixed.

**Comment by ssunkara1** [comment]
This is fixed in #425
