### ISSUE TITLE
Scatter plot example tooltip always shows names, and doesn't filter fields correctly

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#379]
The last two cells of the scatter plot example: 
- show_names=False does nothing (names still show)
- setting the fields to ‘y’ just shows the ‘x’ field!

**Comment by dmadeka** [comment]
its `display_names`, does that not work?

**Comment by jasongrout** [comment]
Perhaps the example just needs to be updated, then (penultimate cell...) https://github.com/bloomberg/bqplot/blob/3dd09694fce17841787bcb0a26b21079d62ee167/examples/Marks/Scatter.ipynb

**Comment by dmadeka** [comment]
yup haha, thats outdated
