### ISSUE TITLE
Missing handler to changes in `padding` property for the `Bars` mark.

### ISSUE THREAD

**Issue by SylvainCorlay** [bloomberg/bqplot#397]

**Comment by dmadeka** [comment]
@SylvainCorlay @ssunkara1 I can add this to #404 the question is, what should we trigger? Since we dont really have partial drawing, the easiest is probably a redraw. 

What do you guys this?

**Comment by SylvainCorlay** [comment]
Yes. I don't there is anything less we can do. It is not a common change anyway.

**Comment by dmadeka** [comment]
Well, maybe if we split setting the x and y, here we can only call one of those functions. But for now #404 calls the redraw.
