### ISSUE TITLE
Support for continuous handler call while dragging.

### ISSUE THREAD

**Issue by KelSolaar** [bloomberg/bqplot#416]
Hi,

I'm maybe overlooking something but I didn't figure out how to have an observed trait (through the `observe` method) to call the handler continuously as dragging occurs for example. At the moment, the handler is getting called right at the end when dragging stops.

Cheers,

Thomas

**Comment by dmadeka** [comment]
@KelSolaar In the Scatter.ipynb notebook, there is an example of how to do this:

``` python

def callback_help(value):
    print(value)

scatter.on_drag(callbacl_help)
```

should do the continuous updating. `on_drag_start` and `on_drag_end` are the other callbacks

**Comment by KelSolaar** [comment]
@dmadeka,

Thanks for replying, it does work, well almost actually: It took me a while to pinpoint what was wrong with my code but basically the `on_drag` and `on_drag_end` method don't seem to be working if you use a `LogScale` for the axis.

**Comment by dmadeka** [comment]
Thats a bug then, thanks for the report!

**Comment by ssunkara1** [comment]
@KelSolaar This issue is fixed. Can you try once when you get time? Thanks!

**Comment by KelSolaar** [comment]
@ssunkara1: Working fine on my end! 

Cheers,

Thomas
