### ISSUE TITLE
not able to figure out why bqplot stops working, and how to make it work again quickly 

### ISSUE THREAD

**Issue by stonebig** [bloomberg/bqplot#46]
hi,

After having removed bqplot, it seems it doesn't want to plot anymore, Ipython stalls and nothing happens.

I don't see any error message, kernerl doesn't want to interrupt itself (remains in non-empty circle mode). Have you a wild guess ? (using current trunk in this try)

![bqplot_blocking](https://cloud.githubusercontent.com/assets/4312421/10607188/0f75c33a-7738-11e5-8e84-bc3780dca130.GIF)

````
!pip list

adodbapi (2.6.0.7)
alabaster (0.7.6)
astroid (1.3.6)
Babel (2.1.1)
backports-abc (0.4)
backports.ssl-match-hostname (3.4.0.2)
baresql (0.7.2)
bcolz (0.11.4)
beautifulsoup4 (4.4.1)
blaze (0.8.3)
blosc (1.2.8)
bloscpack (0.9.0)
bokeh (0.10.0)
Bottleneck (1.0.0)
bqplot (0.3.10.dev0)
brewer2mpl (1.4.1)
castra (0.1.6)
certifi (2015.9.6.1)
cffi (1.2.1)
click (5.0)
colorama (0.3.3)
configparser (3.5.0b2)
cvxopt (1.1.7)
cx-Freeze (4.3.4)
cycler (0.9.0)
cyordereddict (0.2.2)
Cython (0.23.4)
cytoolz (0.7.3)
dask (0.7.3)
datashape (0.4.7)
db.py (0.4.4)
decorator (4.0.4)
dill (0.2.4)
docopt (0.6.2)
docutils (0.12)
enum34 (1.0.4)
Flask (0.10.1)
formlayout (1.0.15)
funcsigs (0.4)
functools32 (3.2.3.post2)
greenlet (0.4.9)
guidata (1.7.0b5)
guiqwt (3.0.0b6)
h5py (2.5.0)
holoviews (1.3.2)
husl (4.0.3)
ipykernel (4.1.1)
ipyparallel (4.0.2)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipython-sql (0.3.7.1)
ipywidgets (4.1.0)
itsdangerous (0.24)
jedi (0.8.1)
Jinja2 (2.8)
joblib (0.9.2)
jsonschema (2.5.1)
julia (0.1.1.8)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.0.3)
jupyter-core (4.0.6)
Keras (0.2.0)
llvmlite (0.6.0)
lmfit (0.9.1)
locket (0.2.0)
logilab-common (1.1.0)
lxml (3.4.4)
Markdown (2.6.2)
MarkupSafe (0.23)
matplotlib (1.5.0rc2)
mingwpy (0.1.0b3)
mistune (0.7.1)
mpld3 (0.2)
multipledispatch (0.4.8)
mysql-connector-python (2.0.4)
nbconvert (4.0.0)
nbformat (4.0.1)
netCDF4 (1.2.1)
networkx (1.10)
nltk (3.0.5)
nose (1.3.7)
notebook (4.0.6)
numba (0.20.0)
numexpr (2.4.4)
numpy (1.9.3)
numpydoc (0.5)
oct2py (3.3.3)
odo (0.3.4)
pandas (0.17.0)
pandas-datareader (0.2.0)
param (1.3.2)
partd (0.3.2)
path.py (8.1.2)
patsy (0.4.0)
pep8 (1.6.2)
pg8000 (1.10.2)
pickleshare (0.5)
Pillow (3.0.0)
pip (7.1.2)
pkginfo (1.2.1)
prettytable (0.7.2)
psutil (3.2.2)
PuLP (1.5.9)
py (1.4.30)
PyAudio (0.2.8)
pybars3 (0.9.1)
pycparser (2.14)
pyflakes (0.9.2)
Pygments (2.0.2)
pyhdf (0.8.3)
pylint (1.4.3)
PyMeta3 (0.5.1)
pymongo (3.0.3)
pyodbc (3.0.10)
PyOpenGL (3.1.0)
pyparsing (2.0.3)
PyQt4 (4.11.4)
PyQtdesignerplugins (1.1)
pyqtgraph (0.9.10)
PyQwt (5.2.1)
pyserial (2.7)
pystache (0.5.4)
pytest (2.8.2)
python-dateutil (2.4.2)
PythonQwt (0.3.0)
pytz (2015.6)
pywin32 (219)
PyYAML (3.11)
pyzmq (14.7.0)
qtconsole (4.1.0)
redis (2.10.3)
reportlab (3.2.0)
requests (2.8.1)
requests-toolbelt (0.4.0)
rope (0.10.2)
rpy2 (2.7.2)
Rx (1.2.3)
scikit-image (0.11.3)
scikit-learn (0.16.1)
scilab2py (0.6)
scipy (0.16.0)
seaborn (0.7.0.dev0)
setuptools (18.4)
simplegeneric (0.8.1)
simplejson (3.8.0)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.9)
spyder (3.0.0.dev0)
SQLAlchemy (1.0.8)
sqlite-bro (0.8.10)
sqlparse (0.1.16)
statsmodels (0.6.1)
sympy (0.7.6.1)
tables (3.2.2)
Theano (0.7.0)
toolz (0.7.4)
tornado (4.2.1)
traitlets (4.0.0)
twine (1.6.3)
twitter (1.17.1)
ViTables (2.1)
Werkzeug (0.10.4)
wheel (0.26.0)
winpython (1.2)
xlrd (0.9.4)
XlsxWriter (0.7.6)
xray (0.6.0)
````

**Comment by SylvainCorlay** [comment]
@stonebig thanks for reporting. Can you please hit "Crtl+Shift+J" in your browser window if you are on Linux or Windows, and "Cmd+Alt+J" if you are on mac and tell me about the JavaScript console errors?

My bet is that you would be missing the d3.js and topojson javascript dependencies. 

If you are running from source, please note that you need to run "bower install" in the bqplot top directory.

**Comment by stonebig** [comment]
````
Starting WebSockets: ws://localhost:8888/api/kernels/58e15ded-ac42-4413-a82f-8ad86c0c3b76
main.min.js:22160 Kernel: kernel_connected (58e15ded-ac42-4413-a82f-8ad86c0c3b76)
main.min.js:22160 Kernel: kernel_ready (58e15ded-ac42-4413-a82f-8ad86c0c3b76)
main.min.js:12030 Loaded extension: widgets/notebook/js/extension
:8888/nbextensions/widgets/notebook/js/extension.js?v=20151020174858:81 loaded widgets
kernel.js:98 Kernel: kernel_restarting (58e15ded-ac42-4413-a82f-8ad86c0c3b76)
kernel.js:98 Kernel: kernel_created (58e15ded-ac42-4413-a82f-8ad86c0c3b76)
kernel.js:440 Starting WebSockets: ws://localhost:8888/api/kernels/58e15ded-ac42-4413-a82f-8ad86c0c3b76
kernel.js:98 Kernel: kernel_connected (58e15ded-ac42-4413-a82f-8ad86c0c3b76)
kernel.js:98 Kernel: kernel_ready (58e15ded-ac42-4413-a82f-8ad86c0c3b76)
require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1926 GET http://localhost:8888/nbextensions/bqplot/components/d3/d3.js?v=20151020174858 404 (Not Found)req.load @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1926context.load @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1667Module.load @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:829Module.fetch @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:819Module.check @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:851Module.enable @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1165context.enable @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1538(anonymous function) @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1150(anonymous function) @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:131each @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:56Module.enable @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1102Module.init @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:783callGetModule @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1192context.completeLoad @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1571context.onScriptLoad @ require.js?v=2de44fdcc1fe5e939aa4ce80626b241d:1699
utils.js:777 WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ utils.js:777
kernel.js:865 Couldn't process kernel message WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ kernel.js:865
utils.js:777 WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ utils.js:777
kernel.js:865 Couldn't process kernel message WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ kernel.js:865
utils.js:777 WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ utils.js:777
kernel.js:865 Couldn't process kernel message WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ kernel.js:865
utils.js:777 WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ utils.js:777
kernel.js:865 Couldn't process kernel message WrappedError {stack: "Error: Couldn't create a model.↵    at new Error (…in.js?v=40e10638fcf65fc1c057bff31d165e9d:12785:33", message: "Couldn't create a model.", error_stack: Array[3]}(anonymous function) @ kernel.js:865
````

**Comment by SylvainCorlay** [comment]
That is it. I think that you are running from source. You need to run bower install to run from source as explained in the readme.

**Comment by stonebig** [comment]
does it mean I must have first npm installed ?

**Comment by SylvainCorlay** [comment]
Yes, node is required to run from source. We will actually soon drop bower and only use npm instead like in ipywidgets.

**Comment by stonebig** [comment]
ok. I can get a node.exe working, and a `npm` also, up to the moment node-gyp will try (and fail) to compile something. https://github.com/nodejs/node-gyp/issues/660

no bqplot if you don't have vs201x (very sad, as mingwpy is now available as a wheel)

**Comment by SylvainCorlay** [comment]
@ssunkara1 has been using npm on windows. He might be able to look at it.

**Comment by stonebig** [comment]
maybe Windows cannot survive the nodejs shift of the Jupyter project

**Comment by stonebig** [comment]
Well, it works again with tonight new release, without nodejs. that's a bit strange to me.

**Comment by SylvainCorlay** [comment]
Let me know if it works with WinPython

**Comment by stonebig** [comment]
I placed a bqplot example in the  winpython_checker.ipynb, seems ok on all versions I do prepare at the moment.

**Comment by SylvainCorlay** [comment]
Are you adding bqplot to winpython?

**Comment by stonebig** [comment]
Yes.

**Comment by SylvainCorlay** [comment]
:birthday:  :tada: :trophy: :tropical_drink: !

**Comment by stonebig** [comment]
something wired happens at the end-of-the-day,  the bqplot doesn't want to display anything, even after reboot. 
![bqplot_showing_uniform_grey_image](https://cloud.githubusercontent.com/assets/4312421/10714668/bbbc1350-7af9-11e5-8de8-d704df9a4583.GIF)

**Comment by stonebig** [comment]
if i delete the extension and I redo `python -m bqplot.install --user --force` the bqplot cell holds the kernel undefinitely.
![bqplot_locking_kernel_forever](https://cloud.githubusercontent.com/assets/4312421/10714690/79064142-7afa-11e5-9ad8-0537635df2be.GIF)

it looks I'm in same situation of 3 days ago. So no clue how I go there, and how it solved itself saturday morning.

**Comment by stonebig** [comment]
I killed the server woth jupyter menu, no effect), closed the window, reclicke on the experience workbook, and then I see the bqplot curve showing immediately (I didn't even launch an action), at cell 1 result , the cell before I actually summon bqplot graphic.
![bqplot_locking_kernel_forever_and_now_is_back_cell_1_instead_of_2](https://cloud.githubusercontent.com/assets/4312421/10714713/43914ad8-7afb-11e5-9149-d9561f8860e6.GIF)

**Comment by stonebig** [comment]
and now if I relaunch the cell with `x = np.linspace(1.0, 10.0, n)`, I get 2 curves:
![bqplot_next02](https://cloud.githubusercontent.com/assets/4312421/10714724/d7fbac54-7afb-11e5-830b-15d3b09224c0.GIF)

**Comment by stonebig** [comment]
so:
- either there is some initialisation I should do because bqplot doesn't die (or live) exactly like the kernel process,
- either there is a bug of some sort.

In any case, there should be a simple workaround, as it seems I can unlock without deleting/re-installing everything

**Comment by stonebig** [comment]
seems that `plt.figure(2)` gets me a new figure.

**Comment by stonebig** [comment]
maybe just a plt.clear() in the front page example https://github.com/bloomberg/bqplot ?
````
from bqplot import pyplot as plt
import numpy as np
plt.clear()
plt.figure(1)
np.random.seed(0)
n = 200
x = np.linspace(3.0, 10.0, n)
y = np.cumsum(np.random.randn(n))
plt.plot(x,y, axes_options={'y': {'grid_lines': 'dashed'}})
plt.show()
````

**Comment by stonebig** [comment]
no, doesn't solve all cases:
![bqplot_next03](https://cloud.githubusercontent.com/assets/4312421/10714763/9d5a335c-7afd-11e5-84f0-6ea69eb87ba0.GIF)

**Comment by SylvainCorlay** [comment]
Hi @stonebig,

The behavior with 1-2 curves and the `figure` command is expected.

1. If you do `figure(x)`, where `x` is anything hashable, it looks for a context named `x`. If there is none, it creates a new blank figure for you. If there is already one, it is returned to you. It is exactly the same behavior than Matlab or Matplotlib (with interactive mode on). In your case, the context figure for the key `1` already had a line chart on it.

2. Calling `figure()` with no argument creates a new blank context figure, which cannot be addressed by key later, like in Matlab.

3. Calling `figure(fig=foobar)` where foobar is an instance of `Figure` makes the specified figure the context figure.

    We third case does not exist in Matlab, and is meant for people who use both the pyplot and the bqplot APIs.

Regarding the issues that you have when updating the JavaScript side, one advice I can give you is to clean the cache of chrome. Chrome's cache is *very* annoying. To do so, you need to open the developer tools (Crtl + Shift + J), then right-click on the reload button and do "Clear cache and hard reload".

**Comment by stonebig** [comment]
by default I play in Firefox. trying to clear cash as 1rst rescue kit

**Comment by stonebig** [comment]
I'm still with this square-grey figure showing nothing... scratching my head

**Comment by SylvainCorlay** [comment]
@stonebig do you run the whole Pyplot example? There is a call to `plt.clear` in this notebook.

**Comment by stonebig** [comment]
yes, in the mean time with your Ctrl+Shift+i then Ctrl+Shift+J , chrome showed the curve agained (but not firefox)

**Comment by SylvainCorlay** [comment]
OK, there might be a firefox-specific issue here :unamused: I will look into it.

**Comment by stonebig** [comment]
````
# bqplot
# if bqplot shows en empty figure and you're on chrome, try <Ctrl>+<Shift>+I then <Ctrl>+<Shift>+J (clear the browser cache) 

from bqplot import pyplot as plt
import numpy as np
plt.close(1)
plt.clear()  # critical detail 
plt.figure(1)
np.random.seed(0)
n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n))
plt.plot(x,y, axes_options={'y': {'grid_lines': 'dashed'}})
plt.show()
````

**Comment by stonebig** [comment]
will the `soon` landing Ipython4.1 make a difference in stability / flawless configurations ?

**Comment by SylvainCorlay** [comment]
The two-step installation procedure is likely to remain until notebook 5.0 is released unless we find a temporary solution in the meantime. With 5.0, extensibility of the front-end is really being reworked and packaging of nbextensions is part it.

Other IPython widget libraries like [pythreejs](https://github.com/jovyan/pythreejs) have exactly the same problem as bqplot and the installation procedure is exactly the same.

However, ipyywidgets 4.2 is probably going to bring changes. Especially with  PR ipython/ipywidgets#193 which should enable the use of IPython widgets (including bqplot) in other web applications than the notebook.

**Comment by SylvainCorlay** [comment]
@stonebig closing this one. There is another issue open for the firefox-specific problem
