### ISSUE TITLE
how to use from client side browser if bqplot is only installed on server side?

### ISSUE THREAD

**Issue by denfromufa** [bloomberg/bqplot#48]
it looks like the javascript and maybe even python code need to be installed on client side when using jupyter notebook server from remote machine?

right now if the javascript code is not installed, the code execution of bqplot just freezes.

this is very confusing for the user.

also when multiple users access the same remote jupyter notebook, then plots seem to break.

**Comment by SylvainCorlay** [comment]
@denfromufa ,  The JavaScript installation procedure is detailed in the [Readme](https://github.com/bloomberg/bqplot/blob/master/README.md). 

You should run
```Bash
python -m bqplot.install --user
```
to get the have the JavaSciprt copied to the right location.

If you are running from source (from a GitHub clone), another step is required (bower install), but it is not necessary if you only installed bqplot from pypi.

**Comment by denfromufa** [comment]
ok, I confirmed that with bqplot uninstalled on client side (including js nbextension), the server side works once in a while. at times it generates an empty plot, but second time I re-open and re-run the notebook, then the plot is fine. very weird. how do I debug this problem?

before on another client machine the code was stuck without plotting. not sure why?

**Comment by SylvainCorlay** [comment]
If you are testing the `Pyplot` notebook, we intentionally clear a plot at some point. Is it what you are seeing?

**Comment by denfromufa** [comment]
ok it seems to be working now, the remove the empty plot I clear outputs and restart kernel:

```
from bqplot import pyplot as plt
import numpy as np
plt.figure(1)
np.random.seed(0)
n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n))
plt.plot(x,y, axes_options={'y': {'grid_lines': 'dashed'}})
plt.show()
```
