### ISSUE TITLE
bqplot stuck on pip install/debian jessie 8

### ISSUE THREAD

**Issue by Haythamamin** [bloomberg/bqplot#481]
I'm trying to install bqplot on debian jessie 8 using the command `sudo -H pip install bqplot`. After collecting dependencies the installation process just gets stuck i.e. never complete the installation.

`Collecting bqplot`
`    Downloading bqplot-0.9.0-py2.py3-none-any.whl (2.2MB)`
`       100% |████████████████████████████████| 2.3MB 67kB/s`
`Collecting numpy>=1.10.4 (from bqplot)`
`    Downloading numpy-1.12.1.zip (4.8MB)`
`       100% |████████████████████████████████| 4.8MB 33kB/s`
`Collecting pandas (from bqplot)`
    `Downloading pandas-0.20.2.tar.gz (10.3MB)`
`       100% |████████████████████████████████| 10.3MB 15kB/s`

Then it goes on forever, please advise.

**Comment by Haythamamin** [comment]
Nevermind, it turns out it just take some really long time to finish the task.

**Comment by SylvainCorlay** [comment]
Sorry for the late reply. I think that the process appeared to be hanging because of the npm build (bundling of the javascript).

This can be really really slow if you are building e.g. from a raspberry pi, and just a minute on a regular computer.

**Comment by SylvainCorlay** [comment]
Thanks for reporting!
