### ISSUE TITLE
Embed a bqplot figure in a webpage.

### ISSUE THREAD

**Issue by frmsaul** [bloomberg/bqplot#491]
Is there a way to export a bqplot a figure in order to embed it in a web page?

**Comment by dmadeka** [comment]
@frmsaul You can do this using the embed widgets option in the menu at the top of the notebook.

![image](https://user-images.githubusercontent.com/7892382/27436137-49c31fc6-572c-11e7-9d5d-da23330ee584.png)

**Comment by dmadeka** [comment]
Hi @frmsaul, you can use the embed widgets option in the menu (under Widgets) at the top of the notebook.

![image](https://user-images.githubusercontent.com/7892382/27436876-8adbfc4c-572e-11e7-88ed-42d7d57a3706.png)
