### ISSUE TITLE
wealth of nations hover behavior is incorrect

### ISSUE THREAD

**Issue by TotalVerb** [bloomberg/bqplot#493]
In the wealth of nations example, the trajectory that is highlighted upon hovering over a data point is not correct.

For example in 2008 if I hover over Equatorial Guinea the trajectory for Eritrea is highlighted. Similarly if I hover over Eritrea, the trajectory for Ethiopia is highlighted.

Equatorial Guinea => Eritrea => Ethiopia => Gabon => Ghana => Guinea => Guinea-Bissau => ...

It looks like perhaps something is offset.

**Comment by dmadeka** [comment]
@TotalVerb Good catch, Ill look at it this weekend, though I think I identify the bug. I believe it's an easy one, maybe @bfelds this can be Fengyang's first contribution?

**Comment by ssunkara1** [comment]
@dmadeka: @TotalVerb has already done this #492 :)

**Comment by dmadeka** [comment]
@ssunkara1 @TotalVerb second contribution~ :/ sorry!
