### ISSUE TITLE
Jupyterlab Beta Ready

### ISSUE THREAD

**Issue by jzf2101** [bloomberg/bqplot#494]
@jasongrout We discussed getting bqplot ready for jupyterlab beta so we could showcase it in the [demo](https://github.com/jupyterlab/jupyterlab-demo). Can we get this ready so it can be included for jupyterlab beta?

**Comment by dmadeka** [comment]
@jasongrout Im also wondering if I can do my entire demo in JupyterLab for SciPy?

**Comment by jasongrout** [comment]
Yes, we can certainly get this ready and working in jlab. JLab is working great these days!

**Comment by jzf2101** [comment]
@jasongrout you mentioned on the jlab gitter that it works now? Can we close this issue?

```
pip install bqplot --pre
pip install ipywidgets --pre
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install bqplot-jupyterlab
```

**Comment by jzf2101** [comment]
@jasongrout when will this be released?

**Comment by jasongrout** [comment]
It is in the newest alpha.

**Comment by OliverEvans96** [comment]
I'm not having any luck here with:

```
jupyterlab 0.25.2
ipywidgets 7.0.0a11
bqplot 0.9.0
@jupyter-widgets/jupyterlab-manager 0.24.5
bqplot-jupyterlab 0.4.0
```

I'm trying the following in a JupyterLab notebook:
```
import bqplot.pyplot as plt
import numpy as np

x = np.linspace(-10,10,1001)
y = x + 3
plt.plot(x, y)
plt.show()
```

and getting 
```
Error displaying widget
```
in the cell output, along with some js console errors:
```
manager-base.js:263 Could not instantiate widget
(anonymous) @ manager-base.js:263
step @ manager-base.js:34
(anonymous) @ manager-base.js:15
rejected @ manager-base.js:7
utils.js:84 Error: Could not create a model.
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
utils.js:84 Error: Could not create a model.
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
lab:1 Uncaught (in promise) Module bqplot, semver range ^0.2.3 is not registered as a widget module
lab:1 Uncaught (in promise) Module bqplot, semver range ^0.2.3 is not registered as a widget module
```

The same code is working in the classic notebook without error.

**Comment by GauNi** [comment]
I have the same error with:
JupyerLab 0.29.1 
 ipywidgets 7.0.3 
bqplot-0.10.0
