### ISSUE TITLE
Trying development installation, having virtual env issues

### ISSUE THREAD

**Issue by dustinmichels** [bloomberg/bqplot#495]
I'm trying to do a developer install of bqplot, inside an anaconda virtual environment. To get a fresh start, I deleted my miniconda3 folder, then reinstalled miniconda, then created a virtual env using `conda create -n <my_name> python`. I tried doing a developer installation of bqplot using:

```
$ git clone https://github.com/bloomberg/bqplot.git
$ cd bqplot
$ pip install -e .
```
This appears to have installed some decencies inside my virtual environment, and some dependencies at root.

When I type the next command listed for dev install, `jupyter nbextension install --py --symlink --sys-prefix bqplot` I get the error `ModuleNotFoundError: No module named 'traittypes'.`

Inside my virtual env, I type `pip freeze` and `conda list` and indeed do not see `traittypes` listed. Outside the env, I type `pip freeze` and I see it listed.

Am I doing something wrong? Or is this an issue with the bqplot setup file? Or it more likely an issue with anaconda?

**Comment by dustinmichels** [comment]
Note: this was easy to fix by pip installing `traittypes` into my conda env-- it's just that the behavior confused me and I wondered if it constituted a bug?

**Comment by ssunkara1** [comment]
Thanks for reporting this @dustinmichels I have tried with conda virtualenv before and I thought it was working fine. I will check that and get back to you. One quick question. What OS are you trying to install and what version of anaconda do you have?

**Comment by dustinmichels** [comment]
Using conda 4.3.21 in Ubuntu!

**Comment by dmadeka** [comment]
@dustinmichels I saw your other issues/questions - did you manage to fix this?

**Comment by dustinmichels** [comment]
Yes, I could fix easily by pip installing `traittypes` into the virtual environment. I just thought it seemed strange that some decencies were getting installed into the virtual env and some into the root, and `traittypes` was initially inaccessible from the virtual env. But that might have to do with Jupyter notebook or ipywidgets or something else outside of bqplot. Feel free to close this issue if that behavior doesn't seem strange to you!

**Comment by dmadeka** [comment]
`traittypes` is a requirement, so I'm not sure what is going on.. @SylvainCorlay might know better, I think he maintains `traittypes`
