### ISSUE TITLE
Customize tooltip for different elements of a mark?

### ISSUE THREAD

**Issue by dustinmichels** [bloomberg/bqplot#498]
Just a question: I'm using the new Graph mark.

```python
tt = Tooltip(fields=node_attrs_list)

graph = Graph(node_data=node_data,
              link_data=link_data,
              link_type='line',
              colors=color_array,
              tooltip=tt,
              directed=False)
```
Instead of adding the same tooltip to all nodes in the graph, I would like to display different tooltip for different nodes (ie, some nodes might have a 'size' attribute, others might not.) Is there any way to do this? Or if not, is there a way to get the tooltip to not display empty attributes?

**Comment by dmadeka** [comment]
You can observe the `hovered point` and change the attributes of the tooltip in the function. it would look something like:

``` python
def check(*args, **kwargs):
    if condition_check_point(graph.hovered_point):
        tt.fields = node_attrs_list_1

graph.observe(check, 'hovered_point')
```

Though, that's a good point, we should allow the user to decide not to display attributes when theyre `None` for the tooltip

**Comment by dustinmichels** [comment]
Perfect, thank you so much!!

**Comment by dmadeka** [comment]
@dustinmichels Great, Im closing this issue. FYI, you can send an entire `Figure` as the tooltip, and use the `hovered_point` to modify it. The examples for the `MarketMap` detail this quite well, this should allow you to display an arbitrary chart for each node.
