### ISSUE TITLE
bqplot stalls ipython(2/3) sessions

### ISSUE THREAD

**Issue by nadavhoresh** [bloomberg/bqplot#50]
When I try any example in a jupyter notebook session either with python2 (2.7.10) or python3 (3.5.0) on either firefox or chromium, the session stalls ---  the circle on the upper right side (menu strip) next to the python 2 (or python 3) label becomes filled and the session becomes unresponsive. This happened after an execution of any bqplot function.

 System: Archlinux on a sandy bridge processor PC.
 bqplot versions: 0.3.9, 0.4.1, and 0.4.2

**Comment by SylvainCorlay** [comment]
@nadavhoresh did you perform the second step of the installation (installing the notebook extension).

**Comment by nadavhoresh** [comment]
OK, my mistake was that I ran the 2nd stage as a root and not as the intended user. maybe it worth while in note in explicitly.


  Thank you very much,

     Nadav.


________________________________

**Comment by SylvainCorlay** [comment]
thanks. Closing. 
(Btw, you should be able to run the second stage as root if you really want, but then you should not use  the `--user` option)
