### ISSUE TITLE
"on_element_click()" does not seem to work for Graph mark

### ISSUE THREAD

**Issue by dustinmichels** [bloomberg/bqplot#500]
When constructing a Graph mark, it seems that I can set a callback function using, for example, `graph.on_background_click(print_event)` but setting a callback using `graph.on_click()` or `graph.on_element_click()` does not seem to do anything.

Really loving the Graph mark! Thank you for all your great work!!

**Comment by dmadeka** [comment]
@dustinmichels It hasn't been implemented yet, but it should be relatively easy to take from the other `Marks`. Do you want to give it a shot?

**Comment by dustinmichels** [comment]
Yes, I would love to!

I'm a little confused about exactly how the Python Mark function--
```python
def on_element_click(self, callback, remove=False):
        self._element_click_handlers.register_callback(callback, remove=remove)
```
-- is interacting with the various places `element_clicked` gets mentioned in the javascript, like in the draw function under ScatterBase.js:
```javascript
draw: function(animate) {
(...)
        elements.on("click", _.bind(function(d, i) {
            this.event_dispatcher("element_clicked",
			      {"data": d, "index": i});
        }, this));
(...)
```

And I'm not sure that my edits to my local javascript files are appearing in my browser, but I'll keep working on this for a while!

**Comment by dmadeka** [comment]
@dustinmichels npm makes local edits super confusing. I think you have to do `--symlink` or follow @maartenbreddels comment in the gitter. As for the `element_clicked` function: the event metadata is registered in `Mark.js`, while on the python side _element_click_handlers is an instance of 

https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget.py#L139

Look into those, and let me know if you have any questions about them!

**Comment by dustinmichels** [comment]
@dmadeka , I am very grateful for your helpful directions, but my knowledge of Node and Javascript is a little scant and I think it will be some time before I'm able to contribute a feature like this.

If anyone else has the time to implement it, it's a feature I would be very grateful for!
