### ISSUE TITLE
Possible to add more d3 color schemes?

### ISSUE THREAD

**Issue by dustinmichels** [bloomberg/bqplot#506]
There is a D3 module that offers some nice, additional categorical color schemes.
https://github.com/d3/d3-scale-chromatic

Is there a nice way to incorporate these into bqplot, so one could pass a name like 'schemePastel1' as the colors argument for Mark? Maybe just adding the hex codes to bqplot/bqplot/colorschemes.py ?

**Comment by dmadeka** [comment]
@dustinmichels We actually depend on d3 3.0, not sure what the compatibility is with 4.0. If so, we'd need to create new scales for each scheme I believe

**Comment by dustinmichels** [comment]
Okay, no problem!

I think its cool to be able to type something like this, and gain access to some "built-in" categorical color schemes, though I'm not sure this is an intended usage:

```python
from bqplot.colorschemes import CATEGORY20
Figure(... colors=CATEGORY20 ...)
```

Nothing urgent, just an idea. Feel free to close this issue if you wish!

**Comment by dmadeka** [comment]
The categorical should be fine! Its the viridis/magma stuff that should be problematic, do you want to try that?

**Comment by dustinmichels** [comment]
Something like this, perhaps? It's just an idea, please feel free to modify or reject!

https://github.com/bloomberg/bqplot/pull/510

**Comment by dustinmichels** [comment]
I'll close this for now. Not a high priority feature. I'll try to submit a more mature variant in the future.
