### ISSUE TITLE
error with bqplot : ImportError: cannot import name 'Graph'

### ISSUE THREAD

**Issue by aktraiser** [bloomberg/bqplot#512]

**Comment by SylvainCorlay** [comment]
Are you attempting to run an example notebook from the master branch with a stable release of bqplot?

**Comment by dmadeka** [comment]
@aktraiser The Graph is in bqplot master and alpha, it isn't part of a stable release yet.

**Comment by aktraiser** [comment]
Thanks,
But there is a another solution for to make node visualisation data?

**Comment by aktraiser** [comment]
i use the bqplot 0.9.0. I love bqplot but i can make node with

**Comment by dmadeka** [comment]
Please use the alpha for bqplot and ipywidgets. Closing this issue!
