### ISSUE TITLE
Could not create model

### ISSUE THREAD

**Issue by Antoine-Cate** [bloomberg/bqplot#515]
I just installed bqplot and tried to run an example. I got the following error. I am not familiar with Java Script at all and could not figure what I did wrong. Thank you a lot for your help!
```
from bqplot import pyplot as plt
import numpy as np

plt.figure(1, title='Line Chart')
np.random.seed(0)
n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n))
plt.plot(x, y)
plt.show()
```
![image](https://user-images.githubusercontent.com/20560702/28630211-a7cec76a-71f7-11e7-9eb8-5b9edc521599.png)

My environment:
# packages in environment at C:\Anaconda:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.4.0                    py35_1  
alabaster                 0.7.10                   py35_0  
anaconda-client           1.6.3                    py35_0  
anaconda-navigator        1.6.3                    py35_0  
anaconda-project          0.6.0                    py35_0  
appdirs                   1.4.2                     <pip>
argcomplete               1.0.0                    py35_1  
asn1crypto                0.22.0                   py35_0  
astroid                   1.4.9                    py35_0  
astropy                   2.0                 np112py35_0  
babel                     2.4.0                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.6.0                    py35_0  
bitarray                  0.8.1                    py35_1  
bkcharts                  0.2                      py35_0  
blaze                     0.10.1                   py35_0  
bleach                    1.5.0                    py35_0  
bokeh                     0.12.6                   py35_0  
boto                      2.47.0                   py35_0  
bottleneck                1.2.1               np112py35_0  
bqplot                    0.9.0                    py35_0    conda-forge
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.10.0                   py35_0  
chardet                   3.0.4                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.7                      py35_0  
climate                   0.4.6                     <pip>
cloudpickle               0.2.2                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.9                    py35_0  
comtypes                  1.1.2                    py35_0  
conda                     4.3.23                   py35_0  
conda-build               3.0.8                    py35_0  
conda-env                 2.6.0                         0  
conda-verify              2.0.0                    py35_0  
configobj                 5.0.6                    py35_0  
console_shortcut          0.1.1                    py35_1  
contextlib2               0.5.5                    py35_0  
cryptography              1.8.1                    py35_0  
curl                      7.52.1                   vc14_0  [vc14]
CVXcanon                  0.1.1                     <pip>
cycler                    0.10.0                   py35_0  
cython                    0.25.2                   py35_0  
cytoolz                   0.8.2                    py35_0  
dask                      0.15.0                   py35_0  
datashape                 0.5.4                    py35_0  
decorator                 4.0.11                   py35_0  
dill                      0.2.6                     <pip>
dill                      0.2.6                    py35_0  
docutils                  0.13.1                   py35_0  
downhill                  0.4.0                     <pip>
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.3                    py35_0  
et_xmlfile                1.0.1                    py35_0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.7                    py35_0  
flask                     0.12.2                   py35_0  
flask-cors                3.0.2                    py35_0  
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0                    py35_0  
gevent                    1.2.2                    py35_0  
glob2                     0.5                      py35_0  
greenlet                  0.4.12                   py35_0  
h5py                      2.7.0               np112py35_0  
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1  
html5lib                  0.999                    py35_0  
icu                       57.1                     vc14_0  [vc14]
idna                      2.5                      py35_0  
imagesize                 0.7.1                    py35_0  
imbalanced-learn          0.1.8                    py35_0    glemaitre
ipykernel                 4.6.1                    py35_0  
ipython                   6.1.0                    py35_0  
ipython_genutils          0.2.0                    py35_0  
ipywidgets                6.0.0                    py35_0  
isort                     4.2.15                   py35_0  
itsdangerous              0.24                     py35_0  
jdcal                     1.3                      py35_0  
jedi                      0.10.2                   py35_2  
jinja2                    2.9.6                    py35_0  
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.6.0                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            5.1.0                    py35_0  
jupyter_console           5.1.0                    py35_0  
jupyter_core              4.3.0                    py35_0  
keras                     2.0.6                    py35_0    conda-forge
Keras                     1.2.1                     <pip>
knnimpute                 0.0.1                     <pip>
lazy-object-proxy         1.3.1                    py35_0  
libdynd                   0.7.2                         0  
libgpuarray               0.6.8                    vc14_0  [vc14]  conda-forge
libpng                    1.6.27                   vc14_0  [vc14]
libprotobuf               3.2.0                    vc14_0  [vc14]
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.19.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.8.0                    py35_0  
mako                      1.0.7                    py35_0    conda-forge
markupsafe                0.23                     py35_2  
matplotlib                2.0.2               np112py35_0  
menuinst                  1.4.7                    py35_0  
mistune                   0.7.4                    py35_0  
mkl                       2017.0.3                      0  
mkl-service               1.1.2                    py35_3  
mpmath                    0.19                     py35_1  
multipledispatch          0.4.9                    py35_0  
multiprocess              0.70.5                    <pip>
nb_anacondacloud          1.4.0                    py35_0  
nb_conda                  2.2.0                    py35_0  
nb_conda_kernels          2.1.0                    py35_0  
nbconvert                 5.2.1                    py35_0  
nbformat                  4.3.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.4                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  5.0.0                    py35_0  
numba                     0.34.0              np112py35_0  
numexpr                   2.6.2               np112py35_0  
numpy                     1.12.1                   py35_0  
numpydoc                  0.6.0                    py35_0  
odo                       0.5.0                    py35_1  
olefile                   0.44                     py35_0  
openpyxl                  2.4.7                    py35_0  
openssl                   1.0.2l                   vc14_0  [vc14]
packaging                 16.8                      <pip>
packaging                 16.8                     py35_0  
pandas                    0.20.2              np112py35_0  
pandocfilters             1.4.1                    py35_0  
partd                     0.3.8                    py35_0  
path.py                   10.3.1                   py35_0  
pathlib2                  2.2.1                    py35_0  
patsy                     0.4.1                    py35_0  
pep8                      1.7.0                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    4.2.1                    py35_0  
pip                       9.0.1                    py35_1  
pip                       9.0.1                     <pip>
pkginfo                   1.4.1                    py35_0  
plac                      0.9.6                     <pip>
ply                       3.10                     py35_0  
prompt_toolkit            1.0.14                   py35_0  
protobuf                  3.3.2               py35_vc14_0  [vc14]  conda-forge
psutil                    5.2.2                    py35_0  
py                        1.4.34                   py35_0  
pyasn1                    0.2.3                    py35_0  
pycosat                   0.6.2                    py35_0  
pycparser                 2.17                     py35_0  
pycrypto                  2.6.1                    py35_6  
pycurl                    7.43.0                   py35_2  
pyflakes                  1.5.0                    py35_0  
pygments                  2.2.0                    py35_0  
pygpu                     0.6.8               np112py35_0    conda-forge
pylint                    1.6.4                    py35_1  
pyopenssl                 17.0.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyparsing                 2.1.10                    <pip>
pyqt                      5.6.0                    py35_2  
pyreadline                2.1                      py35_0  
pytables                  3.2.2               np112py35_4  
pytest                    3.1.2                    py35_0  
python                    3.5.3                         3  
python-dateutil           2.6.0                    py35_0  
pytz                      2017.2                   py35_0  
pywavelets                0.5.2               np112py35_0  
PyWavelets                0.5.1                     <pip>
pywin32                   220                      py35_2  
pyyaml                    3.12                     py35_0  
pyzmq                     16.0.2                   py35_0  
qt                        5.6.2                    vc14_5  [vc14]
qtawesome                 0.4.4                    py35_0  
qtconsole                 4.3.0                    py35_0  
qtpy                      1.2.1                    py35_0  
requests                  2.14.2                   py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14                  py35_1  
scikit-image              0.13.0              np112py35_0  
scikit-learn              0.18.2              np112py35_0  
scipy                     0.19.1              np112py35_0  
scs                       1.2.6                     <pip>
seaborn                   0.7.1                    py35_0  
setuptools                34.3.0                    <pip>
setuptools                27.2.0                   py35_1  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_1  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.6.2                    py35_0  
sphinx_rtd_theme          0.2.4                    py35_0  
sphinxcontrib             1.0                      py35_0  
sphinxcontrib-websupport  1.0.1                    py35_0  
spyder                    3.1.4                    py35_0  
sqlalchemy                1.1.11                   py35_0  
statsmodels               0.8.0               np112py35_0  
sympy                     1.1                      py35_0  
tensorflow                1.1.0               np112py35_0  
testpath                  0.3.1                    py35_0  
theano                    0.9.0                    py35_1    conda-forge
Theano                    0.8.2                     <pip>
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.2                    py35_0  
tornado                   4.5.1                    py35_0  
traitlets                 4.3.2                    py35_0  
traittypes                0.0.6                    py35_0    conda-forge
unicodecsv                0.14.1                   py35_0  
vs2015_runtime            14.0.25420                    0  
watermark                 1.4.0                     <pip>
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.12.2                   py35_0  
wheel                     0.29.0                   py35_0  
widgetsnbextension        2.0.0                    py35_0  
win_unicode_console       0.5                      py35_0  
wrapt                     1.10.10                  py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.6                    py35_0  
xlwings                   0.10.4                   py35_0  
xlwt                      1.2.0                    py35_0  
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by ssunkara1** [comment]
@Antoine-Cate Can you see if you can display any of the `ipywidgets` like an `IntSlider`. The code for that would be:
```
from ipywidgets import IntSlider
IntSlider()
```
Is the slider displayed in this case?

**Comment by Antoine-Cate** [comment]
@ssunkara1 I have no problems with ipywidgets. All sorts of widgets display properly.

**Comment by dmadeka** [comment]
Did you install from conda or pip?

**Comment by Antoine-Cate** [comment]
I installed bqplot using the command diplayed on the readme:
`conda install -c conda-forge bqplot`
I also tried the command following command suggested in the readme and in an other issue I found:
`jupyter nbextension enable --py --sys-prefix bqplot`
It did not change anything about the Create Model problem.

**Comment by dmadeka** [comment]
could you try the pip version, a few people have complained about the conda install @SylvainCorlay  - do we know if there's an issue?

**Comment by Antoine-Cate** [comment]
I uninstalled the conda version, installed the pip version, and I have got the exact same error displaying. I am running on Windows10 with Java 8.0. Thank you for your help!

**Comment by dmadeka** [comment]
@Antoine-Cate Can you try now? We always struggle with ipywidgets updates - they're hard to keep a constant track of

**Comment by josesho** [comment]
Am facing this same problem as well. Any updates re: fixing this? Thanks!

**Comment by dmadeka** [comment]
Everything works for me, what are you ipywidget, bqplot versions?

**Comment by josesho** [comment]
ipywidget=6.0.0
bqplot=0.9.0

**Comment by dmadeka** [comment]
It might be 3.6, @SylvainCorlay ?

**Comment by Ruoxi-Jiang** [comment]
The issue was resolved after I ran:
$ jupyter nbextension enable --py --sys-prefix bqplot
and restart Anaconda

**Comment by Antoine-Cate** [comment]
The issue was also resolved for me after running the above line.
Thanks a million for that!

**Comment by dmadeka** [comment]
@Antoine-Cate You mentioned above that you did run that line, not sure what changed here?

**Comment by Antoine-Cate** [comment]
I installed the last version of bqplot (0.9.0) via PIP. I then run the line (jupyter nbextension enable --py --sys-prefix bqplot) and restarded Jupyter. bqplot works fine since then. I have no idea why and how.
