### ISSUE TITLE
pyplot example notebook fails

### ISSUE THREAD

**Issue by michaelaye** [bloomberg/bqplot#528]
Using 0.9.0 and the notebooks in the examples folder.

For this cell:
```python
plt.figure()
plt.plot(x, y_data)
plt.xlabel('Time')
plt.show()
```
I get a plot but then the error:
```python
AttributeError: module 'bqplot.pyplot' has no attribute 'xlabel'
```

**Comment by rmenegaux** [comment]
Hi Michael,
The `plt.xlabel` feature is not yet available in version 0.9.0, it will be in the next release.

**Comment by dmadeka** [comment]
Usually the notebooks are kept compatible with their version. So if you download the notebook for the release 0.9.0 it shouldn't fail..

**Comment by michaelaye** [comment]
darn, i was afraid the GH master notebooks don't fit the 0.9.0. sorry.
