### ISSUE TITLE
Strange behavior when linking scatter.selected with traitlets.

### ISSUE THREAD

**Issue by dustinmichels** [bloomberg/bqplot#531]
This is perhaps a special and unconcerning case, but inside a class that inherits from `ipywidgets.HBox` I tried linking the selected points on `Scatter` mark to a list of selected points (in a separate, model class) using traitlets, and encountered strange behavior. I essentially wrote:

```python
traitlets.dlink(
    source=(self.model, 'selected_list'),
    target=(self.scatter, 'selected')
)
```
When the model gets a new list of selected points, the selected points on the scatter do indeed update accordingly. However, it turns out that the `scatter.selected` property does *not* update, which caused bugs for me down the line.

I see that the `selected` property is not listed under `scatter.trait_names,` so perhaps this is not a bug at all and I just need to find a different way. But it seemed strange that figure *did* appear to behave the way I wanted it to-- highlighting the appropriate points-- without actually updating the property, so I thought I'd make a note here.

**Comment by dustinmichels** [comment]
Hmm, even when I abandon the traitlets link and set the `scatter.selected` property programmatically from a callback function, I'm still having trouble getting the property to stick.

Now I'm doing something like:

```python
self.model.observe(self._callback, names='selected_list')

def _callback(self, change):
    new_idx_list = change.new
    self.scatter.selected = new_idx_list
```

Once again, the scatter plot updates to reflect the desired list, but the property does not stick-- when I call `self.scatter.selected` later, I get a different value than what is shown in the plot.

Is the behavior you would expect? Perhaps I need to use `hold_sync()` or `hold_trait_notifications()` somewhere?

**Comment by dustinmichels** [comment]
Ah, it looks like simply not setting `interactions = {'click': 'select'}` as a property of the scatter mark fixes my issues-- I can still attach `on_element_click()` to a callback function, and set the selected points the way I want to.

I'll leave this issue open in case any of the behavior I mentioned sounds strange. Thanks!!

**Comment by ssunkara1** [comment]
@dustinmichels This is very strange behavior. Thanks for reporting this.

When you say `self.scatter.selected` does not stick, what is it set to? If you can share a small snippet which reproduces this behavior, that will be very useful. Unless you explicitly click on the chart or on the figure, having `{'click': 'select'}` should not affect the `selected` attribute.

**Comment by dustinmichels** [comment]
I'm not sure there's actually I problem. I was trying to override the default behavior of `{'click': 'select'}`, and I could only get the right behavior when I disabled that interaction.

Anyway, here's a sample notebook:
http://nbviewer.jupyter.org/github/dustinmichels/bqplot/blob/master/examples/Scatter%20Issue.ipynb

(Sorry I couldn't get the plots embedded in nbviewer!)

**Comment by ssunkara1** [comment]
@dustinmichels So after discussion with @jasongrout we agreed that this is a limitation of the current syncing protocol. The behavior is hard to predict if the same property is being set both from the python side and Javascript side and it is resulting in a race condition. By removing `{"click": "select"}` from the `interactions` attribute, we are forcing the `selected` property to be set only from the Python side. Hope this answers your question.

**Comment by dustinmichels** [comment]
Yes, it makes sense! Thanks for taking a look!!
