### ISSUE TITLE
multi x axis when using date as line fig x axis

### ISSUE THREAD

**Issue by cloga** [bloomberg/bqplot#540]
![image](https://user-images.githubusercontent.com/1320343/30061623-a7c1f488-927a-11e7-90fd-b6d8c3b1578f.png)

As you can see above, when I use DateScale for X axis with line fig , it will display two axis value one is date another is number but I don't know where these number come from.

**Comment by dmadeka** [comment]
Can you show us what your syntax was like?

**Comment by cloga** [comment]
# 定义scale
xs = DateScale()
ys = LinearScale()

# 定义悬停显示的内容
tt = Tooltip(fields=['x'], labels=['日期'])

# 定义marker

line = Lines(x=data[data['url_e_c'] == '商学院-精选内容-客户维护']['report_date'].values
             , y=[data[data['url_e_c'] == '商学院-精选内容-客户维护']['pv'].values, data[data['url_e_c'] == '商学院-精选内容-客户维护']['uv'].values]
             , scales={'x': xs, 'y': ys}
             , colors=['red', 'green']
#             , padding=0.2
           , labels=['pv', 'uv']
           , display_legend=True
         , tooltip=tt
             , animate=True
          )
# 定义坐标轴
xax = Axis(scale=xs)
yax = Axis(scale=ys)
# 定义图形
fig = Figure(marks=[line], axes=[xax, yax], legend_location = 'top-right', title='商学院button数据'
             , animate=True, stroke='Black', enable_hover= True, layout=widgets.Layout(width='1000px',height='500px'))

**Comment by ssunkara1** [comment]
@cloga: The issue is that your y axis is also displaying horizontally, overlapping with the x axis. The way to fix this would be:

```
yax = Axis(scale=ys, orientation='vertical')
```

Another alternative is to use `pyplot` which will reduce your code significantly. Equivalent pyplot could would be:

```
from bqplot import pyplot as plt

fig = plt.figure(legend_location = 'top-right', title='商学院button数据'
             , animate=True, layout=widgets.Layout(width='1000px',height='500px'))
line = plt.plot(data[data['url_e_c'] == '商学院-精选内容-客户维护']['report_date'].values,
             [data[data['url_e_c'] == '商学院-精选内容-客户维护']['pv'].values, data[data['url_e_c'] == '商学院-精选内容-客户维护']['uv'].values],
            colors=['red', 'green'], tooltip=tt, display_legend=True, labels=['pv', 'uv'])
plt.show()

**Comment by cloga** [comment]
@ssunkara1 Thank you very much. I think I need to read document carefully, I just think y axis is vertical by default.
