### ISSUE TITLE
0.10 release

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#541]
What issues need to be resolved before a 0.10 release compatible with ipywidgets 7?

CC @dmadeka, @ssunkara1, @SylvainCorlay.

Also CC @stonebig, who I think is interested in a release soon.

**Comment by stonebig** [comment]
I fail to have bqplot-0.10.0a5 working, so an official 0.10.0 would allow me to know if I'm the problem. 

(https://github.com/bloomberg/bqplot/pull/516#issuecomment-326825601 )

**Comment by ssunkara1** [comment]
I want to get #525, #537 in.

**Comment by dmadeka** [comment]
I'd like to get in #480 as well @madridnick

**Comment by dmadeka** [comment]
I'd also like to do a review of selectors, I've been seeing some funky behavior with multiple lines and a date scale

**Comment by stonebig** [comment]
hope for a release before september ends ?

**Comment by jasongrout** [comment]
Let's hold off on #537 to figure out the design there (whether to use the ipywidgets image widget, or do a new one that integrates possibly better). That leaves #525 and #480. 

It looks like #480 is practically done, except for one comment. @madridnick or @ssunkara1 - can one of you make whatever changes needed to merge it, or make a decision that it needs more work and won't be in 0.10?

@rmenegaux - it looks like #525 is about done? @ssunkara1 and @rmenegaux - can you guys look at it if needs any more work, or if we can merge and move on with 0.10?

Otherwise, I think we should just release a 0.10 with what we have, which brings us up to date with ipywidgets 7.0 and solves the tooltip issues. We can always follow up with an 0.11.

**Comment by stonebig** [comment]
in the mean time, still failing to make it work even with  a `jupyter.exe  labextension install bqplot-jupyterlab`

**Comment by jasongrout** [comment]
> Otherwise, I think we should just release a 0.10 with what we have, which brings us up to date with ipywidgets 7.0 and solves the tooltip issues.

Talked with @ssunkara1 yesterday, and we decided to move forward with 0.10 to get widgets 7 compatibility, and we can always cut a 0.11 next week with any new merged PRs.

**Comment by jasongrout** [comment]
I just released 0.10.0...and realized the release instructions say nothing about checking to make sure the examples have the widgets saved :(. 0.10.1 coming up with that.

**Comment by stonebig** [comment]
Is this the valid procedure to have it working on jupyterlab ?
````
pip install bqplot
jupyter nbextension enable --py --sys-prefix bqplot
````

**Comment by jasongrout** [comment]
```
pip install bqplot
jupyter labextension install bqplot-jupyterlab
```
I'm checking it right now too.

**Comment by jasongrout** [comment]
(don't forget to also install the widgets package: `jupyter labextension install @jupyter-widgets/jupyterlab-manager`)

**Comment by stonebig** [comment]
ah, this one is not on your main github readme

**Comment by jasongrout** [comment]
JupyterLab instructions are not in there, right?

**Comment by stonebig** [comment]
apparently, unless I miss my glasses

**Comment by stonebig** [comment]
by the way, shall I do a similar "jupyter.exe nbextension enable --py --sys-prefix bokeh" for bokeh ?

**Comment by jasongrout** [comment]
I have no idea about bokeh

**Comment by jasongrout** [comment]
@stonebig: https://github.com/bloomberg/bqplot/pull/551

**Comment by stonebig** [comment]
cries of joy: bqplot-0.10.0 works  in jupyterlab !

**Comment by jasongrout** [comment]
Me too!
