### ISSUE TITLE
top of AlbersUSA projection gets cut off

### ISSUE THREAD

**Issue by mheilman** [bloomberg/bqplot#550]
When I try to use the Albers USA projection, the top of WA state gets cut off.  It looks like the whole thing should be shifted down a bit, but I'm not sure how to do this.

I see this in `examples/Marks/Map.ipynb`:

<img width="832" alt="screen shot 2017-09-25 at 8 51 45 pm" src="https://user-images.githubusercontent.com/181744/30838802-62bdec5c-a233-11e7-9350-d5bd07108971.png">

If I set `scale_factor` lower (e.g., 800), then I see the whole US, but then there's a lot of empty space in the figure.

some versions:

```
bqplot==0.9.0
ipywidgets==7.0.1
notebook==5.1.0
```

I see the same behavior with the current master branch for bqplot (0.10.0a5, 743a3d6).

**Comment by dmadeka** [comment]
@mheilman We're not sure why this bug came to be, and d3 albersUsa doesn't support centering. https://github.com/d3/d3-3.x-api-reference/blob/master/Geo-Projections.md

What we do currently is just pan the map to center it after we render it. That can be done with the mouse. I can revisit the issue if it's a big deal?

**Comment by mheilman** [comment]
Hmm... I'm not a d3/js expert, but it looks like the map gets rendered on an overly-large SVG element.  Here's a screenshot of the SVG for the map highlighted in chrome.  

![screen shot 2017-09-26 at 10 01 11 am](https://user-images.githubusercontent.com/181744/30869134-065eeb82-a2a6-11e7-8a22-5db227a3b4b2.png)

It looks like the map would show up properly if all of that SVG element were visible, but the `.plotarea_background` ancestor element is causing the edges to be clipped:

![screen shot 2017-09-26 at 10 01 46 am](https://user-images.githubusercontent.com/181744/30869167-18e43fb4-a2a6-11e7-979b-6edf77c4db19.png)

Is there a way to make sure that map SVG element is no bigger than the `.plotarea_background` rectangle?  I fiddled a bit in the map mark JS class but couldn't get it to work.  Any suggestions on what to try?

**Comment by mheilman** [comment]
I spent some time looking into this, and I'm not super-knowledgeable about d3, but it seems like this is something that `fitExtent` (e.g., [here](https://bl.ocks.org/mbostock/5126418) or [here](https://github.com/d3/d3-geo#projection_fitExtent)) would be useful for. As far as I can tell, the path elements are being drawn outside [the SVG for the map](https://github.com/bloomberg/bqplot/blob/a09931d269341e9ca6d0d2344b87f49ce4d6e040/js/src/Map.js#L27), which defines a viewbox from (0,0) to (1200, 980).  It looks like the paths at the edge of the map end up with negative x and/or y values because the projection doesn't know what the viewbox is.

Unfortunately, the version of d3 used by bqplot (3.5.x?) doesn't have that `fitExtent` method. 
 (Thus, this is semi-related to #259.)

I have a temporary workaround using the Albers projection and shifting the paths over, but I'd kinda like to show HI, AK, and PR.

```
projection = bqplot.Albers(center=(-5, 45), scale_factor=2000)
```

Although AlbersUSA doesn't have a `center` method, it does have `translate`, which I think would let me programmatically fix the issue if it were exposed in the `bqplot.AlbersUSA` initializer.

Thoughts?  (Am I way off base here?  As I said, I'm no d3 expert.)

**Comment by mheilman** [comment]
It looks like a very simple fix would be to add a fixed `translate` call [here](https://github.com/bloomberg/bqplot/blob/4b4c0f7939e9f99e9cd526af23df2288a1e7212c/js/src/GeoScaleModel.js#L115) in the `AlbersUSAModel` class:

```javascript
    create_projection: function() {
        this.projection = d3.geo.albersUsa()
            .scale(this.get("scale_factor"))
  	    .translate([600, 490]);  // ADDED
	    this.attribute_changed();
    },
```

The 600 and 490 are half the dimensions of the SVG viewbox that the map goes into.

This appears to work independent of the value of `scale_factor`.

**Comment by dmadeka** [comment]
@mheilman That looks like a good solution to me. But if we're exposing translate, maybe we should make it a trait (something that can be changed from Python). Would you want to submit a PR?

**Comment by mheilman** [comment]
sure, i'll give it a try

**Comment by renanxcortes** [comment]
@mheilman I was having the same problem you mentioned. It seems like bqplot has some default arguments in the Figure function (margins with 60, instead of 0). Please, try to rerun with this:

Figure(marks=[states_map], title='US States Map Example', fig_margin={'top': 0, 'bottom': 0, 'left': 0, 'right': 0})

**Comment by mheilman** [comment]
I didn't have any trouble with this projection after #552 got merged.  Are you using an older version of bqplot?

**Comment by renanxcortes** [comment]
Hm.... my bqplot version is '0.11.1', so I think #552 was already merged. Actually, my default projection was cutting Florida instead of Washington, so the map was a little placed in the 'bottom-right'. But with the fig_margin argument, I was able the place it in the center.
