### ISSUE TITLE
rotation of markers in scatter mark does not seem to work

### ISSUE THREAD

**Issue by oroszl** [bloomberg/bqplot#553]
I ran in to a small problem with regards of Scatter plots. I am trying to emulate interactable arrows, for which I was planning to use Scatter's ability to rotate the markers. I came up with the minimal model 
to get the elucidate the needed coordinate transformations but for some reason rotating has no effect what so ever. So I have the code
```python
import numpy as np
import bqplot as bq
import ipywidgets as ipw

sc=bq.LinearScale(min=-2,max=2)
origin=bq.Scatter(x=[0],y=[0],scales={'x': sc, 'y':sc},colors=['Red'])
endpt=bq.Scatter(x=[0],y=[1],scales={'x': sc, 'y':sc},colors=['Blue'],marker='triangle-up')
fig=bq.Figure(marks=[origin,endpt],layout=dict(width='500px',height='500px'))
def play(y=1,rot=0):
    endpt.rotation=[rot]
    endpt.y=[y]

ipw.interact(play,y=(0,2,0.1),rot=(0,180,1));
fig
```
which produces the expected interaction for marker position but not for marker rotation. Am I doing something wrong ? 

`bq.version_info=(0, 9, 0)`
I installed through conda-forge

**Comment by rmenegaux** [comment]
Did you try adding a rotation scale to the scatter?
`scales={'x': sc, 'y':sc, 'rotation': bq.LinearScale()}`

**Comment by oroszl** [comment]
doing 
```python
origin=bq.Scatter(x=[0],y=[0],scales={'x': sc, 'y':sc,'rotation': bq.LinearScale(min=0,max=180)},colors=['Red'])
```
has no effect

**Comment by oroszl** [comment]
:) great.. my mistake!
