### ISSUE TITLE
Entry for bqplot on awesome-python

### ISSUE THREAD

**Issue by xuanluong** [bloomberg/bqplot#556]
I came across this https://github.com/vinta/awesome-python#data-visualization and thought that it would be nice to have a PR adding `bqplot` to this list.

**Comment by dmadeka** [comment]
@xuanluong Feel free! I dont know much about the awesome lists

**Comment by dmadeka** [comment]
@xuanluong Feel free to upvote! https://github.com/vinta/awesome-python/pull/946

**Comment by xuanluong** [comment]
@dmadeka Just did
