### ISSUE TITLE
scatter selected size

### ISSUE THREAD

**Issue by teffland** [bloomberg/bqplot#557]
I've noticed that there is a way to change the size of a scatter mark on drag. Is this possible to do on selection?

When I try to change it with `selected_style={'fill':'DarkOrange', 'size':100}`, the color changes but the size does not.

**Comment by dmadeka** [comment]
@teffland The selected_style takes a dict of CSS styles - Im not sure there is a way to increase the radius directly from CSS. The way we do it, is listen to `scatter.selected` and modify the `size` attribute - does that work?

**Comment by dmadeka** [comment]
@teffland Does that work? If not, you can make this line an attribute - replace 5 by a trait "drag_size" and add it to the Model and Python.

https://github.com/bloomberg/bqplot/blob/master/js/src/Scatter.js#L294

**Comment by teffland** [comment]
Thanks for the tips! I ended up doing without the effect, so I'm not sure if the solution works, but hopefully this thread will be useful to someone in the future.
