### ISSUE TITLE
resolution of save_png output

### ISSUE THREAD

**Issue by mheilman** [bloomberg/bqplot#558]
It'd be nice to be able to save a figure as a higher resolution PNG than how it shows up in a notebook.  The relevant javascript code is around [here](https://github.com/bloomberg/bqplot/blob/81fb19e3e3d5e54263cbc45b78664fa08b5fc692/js/src/Figure.js#L725).

Instead of that, perhaps the type of the output could be an option so that one could programmatically save to SVG instead of PNG.  That might be an easier change (the code is around [here](https://github.com/bloomberg/bqplot/blob/81fb19e3e3d5e54263cbc45b78664fa08b5fc692/js/src/Figure.js#L756)).

**Comment by rmenegaux** [comment]
Solved in #660 with a save to SVG option
