### ISSUE TITLE
marketmap not working from pandas data frame

### ISSUE THREAD

**Issue by andymcarter** [bloomberg/bqplot#559]
```python
import pandas as pd
import numpy as np
from bqplot.market_map import MarketMap

MarketMap(ref_data=pd.DataFrame(data=np.random.randint(1,11,10)))
```
results in 
```python
TypeError: Could not compare [None] with block values
```

This also occurs with any of the examples in the docs when I try to produce a marketmap. Is there something I am doing wrong in calling this?

pandas 0.20.3
ipywidgets 7.0.1
bqplot 0.10.0

Update: if I comment out any of the ref_data kwargs in the constructor for the marketmap examples, then the map renders fine, but obviously then none of the tooltip data is shown on hover.

![pastedgraphic-1](https://user-images.githubusercontent.com/22293319/31485451-c410d8a2-af2b-11e7-9b54-df60d3ad0d1f.png)

**Comment by andymcarter** [comment]
This appears to be a Safari issue, as it works fine in chrome. Feel free to close, apologies.

**Comment by ssunkara1** [comment]
@andymcarter The tooltip seems to work fine on Safari with bqplot version `0.10.1`. Which version are you using?

**Comment by andymcarter** [comment]
I was using 0.10.0 as mentioned above, upgraded to 0.10.1 via conda-forge and the code in the docs runs correctly.

**Comment by ssunkara1** [comment]
Thanks! Closing the issue.
