### ISSUE TITLE
Labeled data plotting

### ISSUE THREAD

**Issue by SylvainCorlay** [bloomberg/bqplot#57]
An interesting feature of matplotlib which was added recently is the use of labeled data in the plotting function.

i.e. one can do

``` python
some_dict = {
    'elephant': [1, 3, 4],
    'cat': [8, 0, 7],
    'mouse': [3, 3, 3],
}
plt.scatter(data=some_dict, x="elephant", y="mouse")
```

this also works with anything that accepts indexing with "elephant" and "mouse" such as a data frame having such columns. I think this is an interesting feature worth implementing in `bqplot.pyplot`.

**Comment by ssunkara1** [comment]
@SylvainCorlay Yeah that will be very useful. How about implementing it in the Marks itself? I feel it is useful to have other attributes in the`tooltip`.

**Comment by SylvainCorlay** [comment]
@ssunkara good point.

**Comment by SylvainCorlay** [comment]
Or allow this type of binding *with* the marks and axes directly, but not necessarily *in* the mark since we will probably want to enable  binding axis labels etc...

**Comment by ellisonbg** [comment]
I think it would be great to support it, but I would advise using the
data=df keyword argument to pass the data to follow the API of matplotlib,
seaborn and other libraries that are using this approach.

On Fri, Oct 30, 2015 at 9:56 AM, Sylvain Corlay <notifications@github.com>
wrote:

> Or allow this type of binding *with* the marks and axes directly, but not
> necessarily *in* the mark since we will probably want to enable binding
> axis labels etc...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bloomberg/bqplot/issues/57#issuecomment-152532131>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
@ellisonbg thanks. I edited the issue.

**Comment by SylvainCorlay** [comment]
As per discussion with @ssunkara1 , the mark might not be the right place to do this. A figure-level approach might be the right approach.

**Comment by dmadeka** [comment]
FYI @ellisonbg we support this in an mpl style syntax now..

**Comment by SylvainCorlay** [comment]
✨ 🎉 👍 💯
