### ISSUE TITLE
Handling bad points in time series?

### ISSUE THREAD

**Issue by rsignell-usgs** [bloomberg/bqplot#570]
I have a time series with a bad value that I'd like to have `bqplot` not use. 

If I use `numpy.ma.masked`, `matplotlib` works, but `bqplot` doesn't seem to work:
https://gist.github.com/rsignell-usgs/ed8cfdf6ef8267edab7625fddfeaf2fb

![2017-11-12_12-52-20](https://user-images.githubusercontent.com/1872600/32701744-e36f734e-c7a8-11e7-8130-58912a23ee83.png)

Is there another technique I should use?

**Comment by ChakriCherukuri** [comment]
@rsignell-usgs please fill in bad points with np.nan

**Comment by rsignell-usgs** [comment]
Yup!  Thanks!
