### ISSUE TITLE
Error displaying widget JupyterLab 0.29.1

### ISSUE THREAD

**Issue by GauNi** [bloomberg/bqplot#571]
Hello,

I am using JupyerLab 0.29.1 and python 3.5 and ipywidgets 7.0.3
I have installed bqplot-0.10.0 :
 pip install bqplot
 jupyter labextension install @jupyter-widgets/jupyterlab-manager 
jupyter labextension install bqplot-jupyterlab

But into Jupylab I still have the error message : "Error displaying widget" when running an example : http://bqplot.readthedocs.io/en/latest/usage.html

Any solution ? Thank you!

**Comment by tylere** [comment]
I am getting similar behavior with:

```
jupyter_core.__version__ = 4.4.0
jupyter_client.__version__ = 5.1.0
jupyterlab.__version__ = 0.29.1
jupyterlab_launcher.__version__ = 0.5.5
ipywidgets.__version__ = 7.0.3
bqplot.__version__ = 0.10.1

@jupyter-widgets/jupyterlab-manager@0.30.1
bqplot@0.3.0
bqplot-jupyterlab@0.6.0
```

Browser console errors shown when opening JupyterLab:
![image](https://user-images.githubusercontent.com/92862/32984882-eac91a86-cc63-11e7-8781-09e5ca30d3b4.png)

Browser console errors shown when attemting to display bqplot results:
![image](https://user-images.githubusercontent.com/92862/32984893-1546a008-cc64-11e7-9db8-bb9a560b427a.png)

**Comment by tylere** [comment]
Possibly relevant...
It looks like bqplot-jupyterlab@0.6.0 is installing bqplot@0.3.0, while the most recent version of bqplot on npm is 0.3.1 which was released "[for jupyterlab manager compatibility](https://github.com/bloomberg/bqplot/commit/0ec17a8f89063dff6749124ca9c11f2f753cd6a9)".

Unfortunately, I don't know the syntax for jupyter nbextension install-ing a specific npm package version.

├─┬ bqplot-jupyterlab@0.6.0 
│ ├─┬ @jupyter-widgets/jupyterlab-manager@0.27.1 
│ │ ├─┬ @jupyterlab/application@0.10.0 
│ │ │ ├── @jupyterlab/apputils@0.10.0 
│ │ │ ├── @jupyterlab/coreutils@0.10.1 
│ │ │ └── @jupyterlab/services@0.49.0 
│ │ ├─┬ @jupyterlab/docregistry@0.10.0 
│ │ │ ├── @jupyterlab/codeeditor@0.10.0 
│ │ │ └── @jupyterlab/codemirror@0.10.0 
│ │ ├─┬ @jupyterlab/notebook@0.10.0 
│ │ │ └── @jupyterlab/cells@0.10.0 
│ │ ├── @jupyterlab/outputarea@0.10.0 
│ │ ├── @jupyterlab/rendermime@0.10.0 
│ │ └── @jupyterlab/rendermime-interfaces@0.3.1 
│ └─┬ **bqplot@0.3.0** 
│   └── popper.js@1.12.9

**Comment by dmadeka** [comment]
@jasongrout Any ideas?

**Comment by jasongrout** [comment]
There are new instructions for installing bqplot in jupyterlab: https://github.com/bloomberg/bqplot/tree/master/js#jupyterlab

```bash
$ pip install bqplot
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager # install the Jupyter widgets extension
$ jupyter labextension install bqplot
```

**Comment by jasongrout** [comment]
(i.e., `bqplot-jupyterlab` is now outdated, and we should deprecate it)

**Comment by tylere** [comment]
Submitted PR to remove reference to the deprecated package from the installation docs:
https://github.com/bloomberg/bqplot/pull/577
