### ISSUE TITLE
Drawing narrower rectangle markers (Scatterplot)

### ISSUE THREAD

**Issue by andymcarter** [bloomberg/bqplot#580]
```code
from bqplot import pyplot as plt
import numpy as np
y_data = np.cumsum(np.random.randn(30) * 100.0)
plt.figure(title='Scatter Plot with colors')
plt.scatter(y_data, y_data, marker = 'rectangle', stroke_width=0)
plt.show()
```
![image](https://user-images.githubusercontent.com/22293319/33263660-8cc37174-d362-11e7-8785-7f18e5fd05fc.png)

How can I make the rectangles narrower so that they don't overlap? Ideally they would be thin vertical lines. I have tried ```stroke_width=0 ``` which helps a little. ``` default_skew=0.9 ``` can make them narrower but also taller, which I don't want.

**Comment by rmenegaux** [comment]
@andymcarter `default_size` measures the area of the markers, so if you leave it unchanged, making the rectangles narrower will also make them taller.
You can achieve what you want by changing `default_skew` and reducing the `default_size`.

**Comment by andymcarter** [comment]
Thanks for the speedy solution.
