### ISSUE TITLE
Qgrid install breaks bqplot in jupyterlab

### ISSUE THREAD

**Issue by timkpaine** [bloomberg/bqplot#587]
bootstrap 0e08c6e8d1d771f76828:103 GET http://localhost:8888/nullnbextensions/qgrid/0.bundle.js net::ERR_ABORTED
requireEnsure @ bootstrap 0e08c6e8d1d771f76828:103
(anonymous) @ plugin.js:95
exports @ plugin.js:94
WidgetManager.loadClass @ manager.js:143
(anonymous) @ manager-base.js:262
step @ manager-base.js:42
(anonymous) @ manager-base.js:23
(anonymous) @ manager-base.js:17
__awaiter @ manager-base.js:13
ManagerBase._make_model @ manager-base.js:256
(anonymous) @ manager-base.js:246
step @ manager-base.js:42
(anonymous) @ manager-base.js:23
(anonymous) @ manager-base.js:17
__awaiter @ manager-base.js:13
ManagerBase.new_model @ manager-base.js:232
ManagerBase.handle_comm_open @ manager-base.js:144
(anonymous) @ manager.js:82
(anonymous) @ default.js:901
Promise resolved (async)
DefaultKernel._handleCommOpen @ default.js:897
DefaultKernel._onWSMessage @ default.js:729
_ws.onmessage @ default.js:653
manager-base.js:272 Could not instantiate widget
(anonymous) @ manager-base.js:272
step @ manager-base.js:42
(anonymous) @ manager-base.js:23
rejected @ manager-base.js:15
Promise rejected (async)
step @ manager-base.js:16
(anonymous) @ manager-base.js:17
__awaiter @ manager-base.js:13
ManagerBase._make_model @ manager-base.js:256
(anonymous) @ manager-base.js:246
step @ manager-base.js:42
(anonymous) @ manager-base.js:23
(anonymous) @ manager-base.js:17
__awaiter @ manager-base.js:13
ManagerBase.new_model @ manager-base.js:232
ManagerBase.handle_comm_open @ manager-base.js:144
(anonymous) @ manager.js:82
(anonymous) @ default.js:901
Promise resolved (async)
DefaultKernel._handleCommOpen @ default.js:897
DefaultKernel._onWSMessage @ default.js:729
_ws.onmessage @ default.js:653
renderer.js:84 Error displaying widget
renderer.js:85 Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (bootstrap 0e08c6e8d1d771f76828:98)
utils.js:119 Error: Could not create a model.
    at promiseRejection (utils.js:119)
    at <anonymous>
promiseRejection @ utils.js:119
Promise rejected (async)
ManagerBase.handle_comm_open @ manager-base.js:149
(anonymous) @ manager.js:82
(anonymous) @ default.js:901
Promise resolved (async)
DefaultKernel._handleCommOpen @ default.js:897
DefaultKernel._onWSMessage @ default.js:729
_ws.onmessage @ default.js:653
bootstrap 0e08c6e8d1d771f76828:98 Uncaught (in promise) Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (bootstrap 0e08c6e8d1d771f76828:98)
onScriptComplete @ bootstrap 0e08c6e8d1d771f76828:98
Promise rejected (async)
ManagerBase.register_model @ manager-base.js:208
(anonymous) @ manager-base.js:247
step @ manager-base.js:42
(anonymous) @ manager-base.js:23
(anonymous) @ manager-base.js:17
__awaiter @ manager-base.js:13
ManagerBase.new_model @ manager-base.js:232
ManagerBase.handle_comm_open @ manager-base.js:144
(anonymous) @ manager.js:82
(anonymous) @ default.js:901
Promise resolved (async)
DefaultKernel._handleCommOpen @ default.js:897
DefaultKernel._onWSMessage @ default.js:729
_ws.onmessage @ default.js:653
bootstrap 0e08c6e8d1d771f76828:98 Uncaught (in promise) Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (bootstrap 0e08c6e8d1d771f76828:98)
onScriptComplete @ bootstrap 0e08c6e8d1d771f76828:98
Promise rejected (async)
ManagerBase.handle_comm_open @ manager-base.js:149
(anonymous) @ manager.js:82
(anonymous) @ default.js:901
Promise resolved (async)
DefaultKernel._handleCommOpen @ default.js:897
DefaultKernel._onWSMessage @ default.js:729
_ws.onmessage @ default.js:653

**Comment by timkpaine** [comment]
https://github.com/quantopian/qgrid/issues/154

**Comment by jasongrout** [comment]
Let's track this in one place so the conversation is consolidated - maybe over in the qgrid repo issue.
