### ISSUE TITLE
Interface is very verbose, lots of boilerplate, lacks default behavior

### ISSUE THREAD

**Issue by xkortex** [bloomberg/bqplot#588]
I love the look and feel of this library, and I have been looking for replacements to matplotlib. However, I find it frustrating to dig in because of the amount of boilerplate required. 

Contrast

`plt.plot(xs, ys)`

with 

```
sc_x = LinearScale()
sc_y = LinearScale()
scale = {'x': sc_x, 'y': sc_y}

ax_x = Axis(scale=sc_x)
ax_y = Axis(scale=sc_y, orientation='vertical')

line = Lines(x=xs, y=ys, scales=scale)
Figure(marks=[line], axes=[ax_x, ax_y])
```

to achieve virtually the same thing. I would really like to be able to just call `Lines(xs, ys)` and have it know I want a basic line plot with linear axes, and yes of course I want the y-axis vertical. Even `x=` and `y=` feels a bit redundant, 95% of line plots will be taking x and y as the first arguments (or better yet a (Nx2) array with x-y pairs as a single argument). 

Additionally, the docstrings do not give a descriptive prototype, I just see args and kwargs, and thus I have to consult the api documentation to know what goes in there. I realize these may come across as a bit picky, but I think it's small little UX niceties like this that make a library truly shine. Even just wrappers/aliases to emulate matplotlib like functionality/calls. 

![image](https://user-images.githubusercontent.com/4248547/34224608-6a24625e-e591-11e7-8854-ac640cd6c31e.png)

**Comment by dmadeka** [comment]
[Doesn't this work](https://github.com/bloomberg/bqplot/blob/master/examples/Basic%20Plotting/Pyplot.ipynb)?

```python
from bqplot import pyplot as blt

blt.plot(x, y_data)
blt.show()
```

Yes there's an additional `blt.show()` line but I wouldn't say its that much more verbose?

**Comment by xkortex** [comment]
D'oh! How did I not even notice that? I sort of got sucked into the API because all of the examples I had viewed used the more granular Lines interface. `blt.show()` is totally fine by me. 

So sorry!

 Although the `blt.plot` docstring is still just args and kwargs ;)

**Comment by dmadeka** [comment]
@xkortex This one is one me. But I claim ignorance - I have no actual idea how to expose the documentation without over-riding the signature of the decorator itself!

https://github.com/bloomberg/bqplot/blob/master/bqplot/pyplot.py#L242

The decorator here is slightly complicated - it doesn't take a function per se, it returns a decorator that overrides certain attributes. I'm not sure how I would over ride that.

**Comment by xkortex** [comment]
I'm not super savvy on decorators, but I'll take a stab at it. You have:

```
def _process_data(*kwarg_names):
    def _data_decorator(func):
        @functools.wraps(func)
        def _mark_with_data(*args, **kwargs):
                ...
                return func(*data_args, **kwargs_update)
        return _mark_with_data
    return _data_decorator
```

Pandas uses this pattern:

```
def deprecate_kwarg(old_arg_name, new_arg_name, mapping=None, stacklevel=2):
    ...
    def _deprecate_kwarg(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            ...
            return func(*args, **kwargs)
        return wrapper
    return _deprecate_kwarg
```

That looks virtually identical to me.  In fact, I would wager that you may have even studied Pandas' API for inspiration like I am doing now!

~~`@functools.wraps` _should_ behave the same as `@wraps`, but maybe there is some module-level stuff that isn't the same, so that may be worth experimenting.~~ 

[From SO](https://stackoverflow.com/a/10176276/3988037):

```
def log_decorator(log_enabled):
    def actual_decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            if log_enabled:
                print("Calling Function: " + func.__name__)
            return func(*args, **kwargs)
        return wrapper
    return actual_decorator
```

Ok, this is a bit of a head-scratcher. What I would do is put lines like `print("Calling Function: " + func.__name__) + func.__doc__` in the decorator at various levels and see where it is getting lost. I am going to play around with it a bit as well as I have been meaning to get better at using decorators in this fashion.

**Comment by dmadeka** [comment]
@xkortex I remember stepping through the code and seeing absolutely no problem with it

```python
(Pdb) _mark_with_data.__name__
'plot'
(Pdb) _mark_with_data.__doc__
"Draw lines in the current context figure.\n\n    Signature: `plot(x, y, **kwargs)` or `plot(y, **kwargs)`, depending of the\n    length of the list of positional arguments. In the case where the `x` array\n    is not provided.\n\n    Parameters\n    ----------\n    x: numpy.ndarray or list, 1d or 2d (optional)\n        The x-coordinates of the plotted line. When not provided, the function\n        defaults to `numpy.arange(len(y))`\n        x can be 1-dimensional or 2-dimensional.\n    y: numpy.ndarray or list, 1d or 2d\n        The y-coordinates of the plotted line. If argument `x` is 2-dimensional\n        it must also be 2-dimensional.\n    marker_str: string\n        string representing line_style, marker and color.\n        For e.g. 'g--o', 'sr' etc\n    options: dict (default: {})\n        Options for the scales to be created. If a scale labeled 'x' is\n        required for that mark, options['x'] contains optional keyword\n        arguments for the constructor of the corresponding scale type.\n    axes_options: dict (default: {})\n        Options for the axes to be created. If an axis labeled 'x' is required\n        for that mark, axes_options['x'] contains optional keyword arguments\n        for the constructor of the corresponding axis type.\n    figure: Figure or None\n        The figure to which the line is to be added.\n        If the value is None, the current figure is used.\n    "
```

**Comment by dmadeka** [comment]
So @xkortex the issue might be on your side
- the doc shows for me

<img width="714" alt="screen shot 2017-12-29 at 3 51 00 pm" src="https://user-images.githubusercontent.com/7892382/34447244-21b636de-ecb0-11e7-8ee1-9bc0ece9330a.png">
