### ISSUE TITLE
Some ColorBrewer scales fall back to 'RdGn' with OrdinalColorScale

### ISSUE THREAD

**Issue by andymcarter** [bloomberg/bqplot#589]
On the OrdinalColorScale, some ColorBrewer scheme will show correctly (such as 'Set3'), whereas setting the scheme as 'Set2' will fall back to 'RdGn' when the chart is plotted.

```python
size = 100
scale = 100.
x_data = np.random.randint(1,10,size)
y_data = np.random.randint(1,10,size)

x_sc = LinearScale()
y_sc = LinearScale()
c_sc = OrdinalColorScale(scheme='Set2')

ax_x = Axis(label='X', scale=x_sc, grid_lines='solid')
ax_y = Axis(label='Y', scale=y_sc, orientation='vertical', grid_lines='solid')
ax_c = ColorAxis(scale=c_sc, side='right', visible=False)

scatter = Scatter(x=x_data, y=x_data, scales={'x': x_sc, 'y': y_sc, 'color': c_sc})
fig = Figure(axes=[ax_x, ax_y, ax_c], marks=[scatter], title='First Example')
scatter.color = x_data
fig
```

**Comment by andymcarter** [comment]
Changed title

**Comment by rmenegaux** [comment]
Hi Andy,
Not all ColorBrewer schemes are supported. Here is a list of the supported ones:
[
    "Paired", "Set3", "Pastel1", "Set1", 
"Greys", "Greens", "Reds", "Purples", "Oranges", "Blues", 
"YlOrRd", "YlOrBr", "YlGnBu", "YlGn", "RdPu",
"PuRd", "PuBuGn", "PuBu", "OrRd", "GnBu", "BuPu",
"BuGn", "BrBG", "PiYG", "PRGn", "PuOr", "RdBu", "RdGy",
"RdYlBu", "RdYlGn", "Spectral"
]
Notice "Set2" is absent.

@ssunkara1 any ideas?

**Comment by andymcarter** [comment]
Thanks- where did you pull the list from? adding set2 and dark1 would be great. Would it be an easy first python PR to add them?

I was hunting for names from this list:
https://matplotlib.org/examples/color/colormaps_reference.html

**Comment by dmadeka** [comment]
@andymcarter @rmenegaux  I think this is a bug:

Set2 is implemented here: https://github.com/bloomberg/bqplot/blob/master/js/src/colorbrewer.js

Otherwise, I think we should be able to add this no problem. Just add a color there - and expose it.

**Comment by andymcarter** [comment]
I shall leave it to the experts for the change. Thanks for the feedback.

**Comment by ssunkara1** [comment]
Yeah this has to be changed. Ideally we shouldn't have to maintain the copy of the list of the color from colorbrewer. It will always lag behind whenever colors are added to colorbrewer as we get the latest version of colorbrewer.

**Comment by dmadeka** [comment]
@ssunkara1 @rmenegaux I was thinking - we need a better implementation of color as a whole. How about we depend on d3-scalechromatic. If we use their interpolators, we lose dependency on hard coding colors, pinning scales to a begin, middle, end and we get the new CAM02 spaces to interpolate in!
