### ISSUE TITLE
Add click event on line marks

### ISSUE THREAD

**Issue by albop** [bloomberg/bqplot#598]
I'm trying to capture click events on data points in the following way:

```
from bqplot import pyplot as plt
pl = plt.plot([0,1,2],[0,1,4],'o')
pl.on_click(lambda x: print(x))
#pl.observe(lambda x: print(x["name"]))
plt.show()
```

Nothing happens when I click on one of the three data points (using Jupyter notebook). Using the commented line instead, I get a list `hovered` and `locked_property`  events but no click. I recall having done that in the past. Is that a regression ?

**Comment by DougRzz** [comment]
Hi albop,

Does this do what you want?

```python
from bqplot import pyplot as plt
pl = plt.plot([0,1,2],[0,1,4],'o')

pl.on_element_click(lambda self, x: print(x))
plt.show()
```
Using the lambda thingy does feel very natural to me.   :smiley:

![image](https://user-images.githubusercontent.com/3510318/35153581-038aba02-fd1f-11e7-86ff-caf3bad70545.png)

**Comment by albop** [comment]
Yes it does. Thank you @dougrzz !
