### ISSUE TITLE
Mapping Mark colors based on dataframe values

### ISSUE THREAD

**Issue by andymcarter** [bloomberg/bqplot#608]
I am trying to enforce a color mapping for a bar chart based on a pandas DataFrame column. I would like to get a consistent color mapping from one string value to a color. See example below.

Sometimes the color scheme comes out the correct way, but sometimes not! I guess it is based on the ordering of the values in the `bar.color` array.

How can I **enforce** 'Y' mapping to 'Red' and 'N' mapping to 'Blue'?

```python

from bqplot import *
import pandas as pd
x_ord = OrdinalScale()
y_sc = LinearScale()
col_sc = OrdinalColorScale(colors=['Red', 'Blue'])


df = pd.DataFrame(index=range(4), columns=['A', 'B'])

df['A'] = range(2, 6)
df['B'] = ['Y', 'N', 'Y', 'N']

bar = Bars(x=df.index, y=df['A'], scales={'x': x_ord, 'y': y_sc, 'color':col_sc})
bar.color = df['B'].values
ax_x = Axis(scale=x_ord)
ax_y = Axis(scale=y_sc, tick_format='0.2f', orientation="vertical")

Figure(marks=[bar], axes=[ax_x, ax_y])
```

**Comment by DougRzz** [comment]
Switching between
```python
bar.color = df['B'].replace('Y','Red').replace('N','Blue')
```
and
```python
bar.color = df['B'].replace('N','Red').replace('Y','Blue')
```
successfully changes the colours for me.

**Comment by andymcarter** [comment]
Thanks @DougRzz, I did try this when you mentioned in Gitter but didn't seem to have an effect. 

I'm getting some really bizarre behaviour where colours don't seem to align with the correct bars. Try this example with three colours, which order do they appear? I would expect to see two blue bars, two yellow and one green (left to right), but that doesn't match.

```python
from bqplot import *
import pandas as pd
x_ord = OrdinalScale()
y_sc = LinearScale()
col_sc = OrdinalColorScale(colors=['Yellow', 'Blue', 'Green'])

df = pd.DataFrame(index=range(5), columns=['num', 'alpha'])

df['num'] = range(2, 7)
df['alpha'] = ['X', 'X', 'Y', 'Y', 'Z']

bar = Bars(x=df.index, y=df['num'], scales={'x': x_ord, 'y': y_sc, 'color':col_sc})
ax_x = Axis(scale=x_ord)
ax_y = Axis(scale=y_sc, tick_format='0.2f', orientation="vertical")

bar.color = df['alpha'].replace('X','Blue').replace('Y','Yellow').replace('Z', 'Green').values

Figure(marks=[bar], axes=[ax_x, ax_y])
```

![image](https://user-images.githubusercontent.com/22293319/36146357-47494d08-10ac-11e8-90a2-8ae88d78ef3c.png)

**Comment by DougRzz** [comment]
Think I found it..........

```python
bar.colors = df['alpha'].replace('X','Blue').replace('Y','Yellow').replace('Z', 'Green').tolist()
```

bar.color -->  bar.colors
.values --> .tolist()

![image](https://user-images.githubusercontent.com/3510318/36151556-95563994-10bf-11e8-9a25-2accdb8863c0.png)

**Comment by andymcarter** [comment]
That's got it, thanks!
