### ISSUE TITLE
BrushIntervalSelector cannot do y selection

### ISSUE THREAD

**Issue by maartenbreddels** [bloomberg/bqplot#616]
You'd expect this if you give it the scale for the y axis.

**Comment by SylvainCorlay** [comment]
OK, actually the scale for the y axis could also be used for the x axis on another chart, so the vertical or horizontal direction of the interval selector could be a trait attribute.

**Comment by maartenbreddels** [comment]
Yes, this information is indeed not in the scale, would make sense to me. Maybe sth similar to axis' `orientation='vertical'` for consistency?

**Comment by SylvainCorlay** [comment]
I think that it would make sense for a brush / interval to have a `orientation` trait, but not in the scale.

The same scale instance can be used for `x` in one chart, `y` in another and a bubble radius in the last...

**Comment by maartenbreddels** [comment]
Indeed, that's what I meant.

**Comment by SylvainCorlay** [comment]
OK, it makes sense!

**Comment by mwcraig** [comment]
Is this closed by #634?

**Comment by SylvainCorlay** [comment]
Yes! Thanks for pointing this out!
