### ISSUE TITLE
Inverting color scales

### ISSUE THREAD

**Issue by rmenegaux** [bloomberg/bqplot#620]
The colorbrewer scales go from light to dark, whereas the matplotlib ones (viridis, magma etc...) go from dark to light. For consistency it would be best if all our color scales went the same way. So... which do we invert? Colorbrewer or matplotlib?

Changing the colorbrewer order would mean changes in a lot of existing code, so I think inverting the matplotlib ones would make more sense. Open to suggestions.

**Comment by SylvainCorlay** [comment]
However, inverting the colorbrewer ones would allow removing calls `invert` in the examples, and let people obtain consistent results with bqplot and matplotlib.

**Comment by dmadeka** [comment]
Matplotlib supports an `_r` option for most colormaps that reverses them. Can we also support that?

**Comment by dmadeka** [comment]
@rmenegaux ?

**Comment by rmenegaux** [comment]
Good point though concerning matplotlib, they do keep the colorbrewer as is and have colorscales going in both ways. We already have a `reverse` option for all scales, including color ones. 
Closing this.
