### ISSUE TITLE
Feature: Support setting OHLC stroke color the same as the fill color

### ISSUE THREAD

**Issue by paulperry** [bloomberg/bqplot#622]
I don't see a way to change the OHLC stroke color on a per candle basis to match the fill color.  For the charts that I look at this is a common style and can attach sample pics of what I'm trying to achieve.

**Comment by rmenegaux** [comment]
Hi @paulperry, the fill color can't be changed on a per candle basis either. I'm guessing you want all the color attributes (`stroke`, `box_fill_color`, `outlier_fill_color`) to be lists?

**Comment by paulperry** [comment]
For full control, making the color attributes as lists is one way to go.  This would help for example in setting colors across multiple charts, e.g. a volume bar chart to the same colors as the candles.  Short of that, passing a flag to OHLC to request that the `stroke` color be the same as the `box_fill_color` would suffice. Here is an example chart I'm trying to reproduce:

<img width="915" alt="gdax_candles" src="https://user-images.githubusercontent.com/501736/37167273-76130d42-22cf-11e8-8408-9184dbe77f1b.png">

**Comment by dmadeka** [comment]
GDAX! :)

**Comment by rmenegaux** [comment]
For this kind of plot fixing the colors manually doesn't seem too bad:
```python
box.stroke = 'red'
box.box_fill_color = 'red'
```
An issue for the green box plot in the picture is that `box_fill_color` cannot be set to `None`, and that `opacities` applies to both fill and stroke, so I don't think we can have a transparent fill for now.

I'll add the possibility for `box_fill_color` to be `None`, then we can look into making these attributes lists, like they are for `Scatter` and `Lines` for example

**Comment by paulperry** [comment]
I didn't think of splitting the price data into two OHLC's on the same Figure, and that works.  And setting the colors to `None` works. 
```
from bqplot import *
import numpy as np
import pandas as pd
price_data1 = [['2015-01-02 00:00:00', [161.31, 163.31, 161.0, 162.06]],
              ['2015-01-05 00:00:00', [161.27, 161.27, 159.19, 159.51]],
              ['2015-01-06 00:00:00', [159.67, 159.96, 155.17, 156.07]],
              ['2015-01-07 00:00:00', [157.2, 157.2, 154.03, 155.05]],
              ['2015-01-08 00:00:00', [156.24, 159.044, 155.55, 158.42]],
              ['2015-01-09 00:00:00', [158.42, 160.34, 157.25, 159.11]],
              ['2015-01-12 00:00:00', [159.0, 159.25, 155.76, 156.44]],
              ['2015-01-13 00:00:00', [157.26, 159.97, 155.68, 156.81]],
              ['2015-01-14 00:00:00', [154.86, 156.49, 153.74, 155.8]],
              ['2015-01-15 00:00:00', [156.69, 156.97, 154.16, 154.57]]]
# Split up the data into x and y points
from bqplot.traits import convert_to_date

dates1 = convert_to_date([d[0] for d in price_data1])
prices1 = [d[1] for d in price_data1]
prices = pd.DataFrame(prices1, index=dates1, columns=list('OHLC'))
prices_low = prices[prices.O > prices.C]
prices_high = prices[prices.O <= prices.C]

sc = LinearScale()
dt_scale = DateScale()
ax_x = Axis(label='X', scale=dt_scale, grid_lines='none')
ax_y = Axis(label='Y', scale=sc, orientation='vertical', tick_format='0.0f', grid_lines='none')

# Construct the marks
ohlc = OHLC(x=prices_low.index, y=prices_low, scales={'x': dt_scale, 'y': sc}, format='ohlc',
            stroke='red', colors=['green','red'])
ohlc2 = OHLC(x=prices_high.index, y=prices_high, scales={'x': dt_scale, 'y': sc}, colors=[None, 'red'],
            stroke='green', format='ohlc')
Figure(axes=[ax_x, ax_y], marks=[ohlc, ohlc2], background_style={'fill': 'black'})
```
![image](https://user-images.githubusercontent.com/501736/37178742-66dc1fcc-22f1-11e8-8fc0-4b4ede881ef9.png)

**Comment by rmenegaux** [comment]
@paulperry glad you worked it out, closing this issue.
