### ISSUE TITLE
error on labels with horizontal bars

### ISSUE THREAD

**Issue by NM4455** [bloomberg/bqplot#643]
Hi,
I'm working with horizontal bars and unfortunately the labels don't work as expected.

The graph is correctly directed according the X axis. However, the labels remains the one previewed for the vertical graph (see picture), even if we change the orientation to "vertical" or "horizontal"
![histogram2](https://user-images.githubusercontent.com/20833027/39522852-e3890092-4e13-11e8-84cf-2dfe21cf0346.PNG)

Here is the code:

```

x_labels = ['aaa','bbb','ccc']
x_ord = OrdinalScale()
y_sc = LinearScale()
y_sc.max = 100
bar = Bars(x= x_labels, y=[0,2,5], scales={'x': x_ord, 'y': y_sc},orientation="horizontal" )

ax_x = Axis(scale=x_ord, orientation="vertical", color = 'Black')
ax_y = Axis(scale=y_sc, tick_format='0.2f', color = 'White')

labels = Label(x=x_labels , y=[0,2,5],scales={'x': x_ord, 'y': y_sc},orientation="vertical", text=[0,0,0], colors=['blue','blue', 'blue'], default_size=24,  update_on_move=True)
histogram = Figure(marks=[labels,bar], axes=[ax_x,ax_y],  background_style = {'fill': 'White'},title=total)


```
Any ideas to have the labels in front of each horizontal bar?

Many thanks in advance,

Nicolas

**Comment by DougRzz** [comment]
You have to swap the x and y on the label mark, Also swap the x&y for scales too. You might also have to adjust the x and y offset.

```python
 Label(y=x_labels, x=[0,2,5], scales={'y': x_ord, 'x': y_sc}, 
    x_offset = 2, y_offset = 7, 
    text=[0,0,0], colors=['blue','blue', 'blue'], 
    default_size=24,  update_on_move=True)
```

**Comment by NM4455** [comment]
it works, thanks!
