### ISSUE TITLE
PR commit handling

### ISSUE THREAD

**Issue by dmadeka** [bloomberg/bqplot#646]
Most repos squash a PR's commits into a single one. Should we do something similar?

**Comment by SylvainCorlay** [comment]
I don't think so. Sometimes a PR has a lot of work and we want the contributor to be credited for it (especially new people) although it should be reasonable. 

Finally, sometimes, multiple commits truly represent very different things that are interested to separate especially for git bisects when looking for breakages.

**Comment by SylvainCorlay** [comment]
(Closed the issue as I am doing some triage / labelling)
