### ISSUE TITLE
Systematically use pyplot in all example notebooks

### ISSUE THREAD

**Issue by ChakriCherukuri** [bloomberg/bqplot#648]
For bqplot to be adopted by users, we should systematically use pyplot (and not the object model) in *all* our example notebooks. Using pyplot reduces the LOC to half compared to the object model.

I am constantly hearing complaints (both internally within Bloomberg and externally too) about the verbosity of the object model for plotting even simple charts. Even for complex plotting and integrating with other widgets pyplot works just fine. If not, it's very easy to enhance pyplot to take care of any missing features.

**Comment by SylvainCorlay** [comment]
This has been fixed in #650.
