### ISSUE TITLE
Boxplot not centered on labels

### ISSUE THREAD

**Issue by mrinalraghupathi** [bloomberg/bqplot#649]
I run the following code and the output below it is what I get, I would have guessed that the boxes align with the labels. Also doesn't seem to be a way to change the font of the tick labels.

```python
import bqplot
x_sc = bqplot.OrdinalScale(domain = ["a","b","c"])
y_sc = bqplot.LinearScale()

xa = bqplot.Axis(scale = x_sc, orientation = 'horizontal')
ya = bqplot.Axis(scale = y_sc, orientation = 'vertical')

bp = bqplot.Boxplot(x=["a","b","c"], y = [[1,2,3,4], [3,4,-1,2], [2,2,3,5]], scales = {'x':x_sc, 'y':y_sc})



fig = bqplot.Figure(marks = [bp], axes = [xa, ya], title = 'A boxplot', title_style={'font-family' : 'Times', 'font-size': '16'})

fig
```

![image](https://user-images.githubusercontent.com/864553/40216716-45f5091e-5a1d-11e8-8397-62150703c5f1.png)

**Comment by SylvainCorlay** [comment]
Thanks! this is now fixed on master. A release is coming out soon!
