### ISSUE TITLE
Can not change marker size and opacity in scatter plot.

### ISSUE THREAD

**Issue by sergeyfridrikh** [bloomberg/bqplot#651]
It looks exactly like the tool I need.
The first experience was not very encouraging. The size and opacity of scatter plot markers did not react to the commands used in pyplot. Could you give me some hints on how to do it?

**Comment by andymcarter** [comment]
I have not used pyplot much, I prefer the full grammar of graphics interface but I admit this has a steep learning curve. I am certainly no expert.

You should be able to modify the scatter opacities through

1) accessing the current figure 
2) Access the first set of marks
3) Set the default_opacities attribute to a single valued list

plt.current_figure().marks[0].default_opacities = [0.5]

**Comment by martinRenou** [comment]
I think this issue can be closed @SylvainCorlay

**Comment by martinRenou** [comment]
This can be closed @ibdafna Thanks!!
