### ISSUE TITLE
citation for SciPy paper

### ISSUE THREAD

**Issue by jmmease** [bloomberg/bqplot#654]
Hi All, 
I've submitted the first draft of a paper for SciPy 2018 on bringing ipywidgets support to plotly.py.
scipy-conference/scipy_proceedings#395 (Current PDF is attached to main description).

I mention bqplot on the second page:
> The infrastructure behind the built-in ipywidgets is available to library authors and many custom ipywidgets libraries have been developed [Cus]. Three notable data visualization examples include bqplot [bqp] for 2-dimensional Grammar of Graphics [Wil05] style visualizations, ipyvolume [ipyb] for 3-dimensional and volumetric visualizations, and ipyleaflet [ipya] for geographic visualization.

Where the [bqp] reference is https://github.com/bloomberg/bqplot

Let me know if you'd like any changes in the citation, or if you'd suggest a different brief description.

Thanks, and feel free to close this issue if you're fine with what's there or if you don't care to review it!

**Comment by jmmease** [comment]
Done in https://github.com/scipy-conference/scipy_proceedings/pull/395/commits/c85d0e968abc6ee4837b2db4860645fd9e40cdc3
Thanks!

**Comment by jasongrout** [comment]
> (@jasongrout you should author a commit :))

/me sees "99 commits" - challenge accepted!
