### ISSUE TITLE
Changing a tooltip label or format is not reflected in graph

### ISSUE THREAD

**Issue by JuanCab** [bloomberg/bqplot#668]
If a change a tooltip label in a Scatter plot called `foo` by performing:

`foo.tooltip.labels[1] = 'new'`

I can confirm the label has changed by checking the value of `foo.tooltip.labels`, but it is not reflected in the tooltip as seen on the Figure, which retains the original label.  Are tooltip labels not meant to be written to after they are created?

I see a similar behavior when I attempt to change `foo.tooltip.formats[1]`.

**Comment by rmenegaux** [comment]
Hi @JuanCab, in the current `traitlets` implementation, changes on a `List`-like trait trigger events only if the whole list is changed, not one of its elements. 
In your case you want to do something like `foo.tooltip.labels = ['old0', 'new1']`
