### ISSUE TITLE
Custom color maps/color scales

### ISSUE THREAD

**Issue by OlehKSS** [bloomberg/bqplot#670]
Is it possible to create and use custom color maps/schemes with `bqplot`, similar to `matplotlib:ListedColorMap`? I want to display color map like on the picture. Thanks.

![Custom Color Map](https://files.gitter.im/maartenbreddels/ipyvolume/FEnW/image.png)

**Comment by rmenegaux** [comment]
Yes, just pass the list of colors to the colorscale, `ColorScale(colors=your_list)`.

You can check out the <a href=https://github.com/bloomberg/bqplot/blob/master/examples/Scales/Color%20Scales.ipynb> ColorScale example notebook</a> for more details

**Comment by OlehKSS** [comment]
Thank you, I have tried it. Nevertheless, I have some problems with it. As far as I understand `ColorScale(colors=your_list)`  takes into account only first three colors from the list, right? This type of behavior wasn't mentioned in documentation. I couldn't plot diverging/centered color maps with 5 control points, but I could do it for three control points. Is there a way to plot a color map with 5 control points?

**Comment by maartenbreddels** [comment]
Could it be that the min and max aren't set property?

**Comment by OlehKSS** [comment]
I have used default values for min an max properties, so min should be minimum of the domain and max will be maximum of the domain.

**Comment by maartenbreddels** [comment]
Can you play with that to see if it can fix it. It might be a bug, I think d3 colorscales, if you give them a list of colors, behave (to me at least) a bit odd, they don't go from [0, 1] to the colors, but from [0, n] (where n is len(colors))

**Comment by rmenegaux** [comment]
@OlehKSS this is one of the issues addressed in PR #605. You should be able to have any number of colors with the latest version.

**Comment by OlehKSS** [comment]
@rmenegaux 
Do you have an example on how to create this plot? 
![](https://user-images.githubusercontent.com/9288961/35828768-061d2dcc-0ac1-11e8-85b6-4bcf019786af.png)

It looks like what I need.

**Comment by SylvainCorlay** [comment]
@OlehKSS yes, you should be able to do that with the current state of master.

We should be releasing a new bqplot version soon!
