### ISSUE TITLE
Delete key on lasso selector doesn't delete lasso

### ISSUE THREAD

**Issue by mwcraig** [bloomberg/bqplot#676]
When I select a lasso and then hit the closest thing I have to a delete key on my mac (the one labelled "Delete") the lasso doesn't delete. The delete key on my mac returns `event.keyCode` of `8` (key name is "Backspace").

**Comment by rmenegaux** [comment]
Hi @mwcraig, to trigger the delete event with a Mac keyboard you need `fn + Backspace`, that should work as expected.
