### ISSUE TITLE
Cannot resize figure with ipywidgets.Box()

### ISSUE THREAD

**Issue by tiagopereira** [bloomberg/bqplot#688]
I'm probably doing something wrong, but I seem to be unable to constrain the dimensions of a bqplot figure using `ipywidgets.Box`. Using `Layout` to set things like width or height only resizes the box where the figure is drawn, not the figure itself! 

For example, if I do:
    
    Box([my_figure], layout=Layout(height='200px', border='1px dashed black'))

I obtain:
![screen shot 2018-07-24 at 17 26 27](https://user-images.githubusercontent.com/1014003/43149750-8ccea522-8f68-11e8-8fc6-115a62cfab2b.png)

and need to scroll vertically to see the bottom of the figure. On the other hand, if I use `VBox` instead, it works as intended:

    VBox([my_figure], layout=Layout(height='200px', border='1px dashed black'))

This gives me something like:

![screen shot 2018-07-24 at 17 26 45](https://user-images.githubusercontent.com/1014003/43149816-b6d2f242-8f68-11e8-91f8-35ac6d5c7ce7.png)

Maybe there's a better option for resizing, but after trying many of the flex options I could not find it. The problem is if I want to set both width and height, I'm stuck because `VBox` doesn't respect the width and stacking a `VBox` with an `HBox` doesn't do the trick.

**Comment by rmenegaux** [comment]
Don't really know why this is happening, but a quick fix is to set `my_figure.layout = {'height': '100%'}`. That makes sure the figure occupies the height given by its parent element.

**Comment by tiagopereira** [comment]
Thank you, that seems to make this issue go away. I forgot to mention that this is happening in JuputerLab (0.32.1), haven't tried in Jupyter notebook. My ipywidgets version is 7.2.1.

**Comment by martinRenou** [comment]
This should be fixed now with the latest version, this issue can be closed. @SylvainCorlay

**Comment by martinRenou** [comment]
@ibdafna
