### ISSUE TITLE
Axis position is not updated when `fig_margin` is changed

### ISSUE THREAD

**Issue by kaiayoung** [bloomberg/bqplot#689]
If `fig_margin` is changed on a figure after is has been displayed, the axis will not adjust to the new position:
```
from bqplot import *
x_data = [1,2,3]`
y_data = [4,5,6]
x_sc, y_sc = OrdinalScale(), LinearScale()
bar = Bars(x=x_data, y=y_data, scales={'x': x_sc, 'y':y_sc})
ax_x = Axis(scale=x_sc)
ax_y = Axis(scale=y_sc, orientation='vertical')
chart = Figure(marks=[bar], axes=[ax_x, ax_y], fig_margin={'bottom': 100, 'top': 20, 'left': 20, 'right': 20})
chart
```

After this cell is run, run the following in the next cell:
`chart.fig_margin = {'bottom': 200, 'top': 20, 'left': 20, 'right': 20}`
![screen shot 2018-07-26 at 10 26 25 am](https://user-images.githubusercontent.com/26637211/43277946-762d8de0-90be-11e8-8ff6-ba85b6cea65e.png)

**Comment by SylvainCorlay** [comment]
Thanks for reporting!
