### ISSUE TITLE
Documentation not showing API reference

### ISSUE THREAD

**Issue by tiagopereira** [bloomberg/bqplot#695]
Currently, the [documentation on readthedocs](https://bqplot.readthedocs.io/en/stable/api_documentation.html) is not showing the API Reference Documentation. At least two weeks ago this was working. Search engines still reference some of the API auto generated tables (e.g. see cache), but the pages have disappeared.

**Comment by SylvainCorlay** [comment]
Thanks! This is back up on the `latest` version

https://bqplot.readthedocs.io/en/latest/api_documentation.html

Closing. (The link in the readme now points at the latest)
