### ISSUE TITLE
[DEMOS] Relative hyperlinks not rendered correctly in Index.ipynb

### ISSUE THREAD

**Issue by rs2** [bloomberg/bqplot#704]
![image](https://user-images.githubusercontent.com/4407787/43953052-bb7fa0a4-9c8f-11e8-980c-202c7696c7c0.png)

[Demo link](https://mybinder.org/v2/gh/bloomberg/bqplot/stable?filepath=examples/Index.ipynb)

**Comment by SylvainCorlay** [comment]
Thanks! It seems that we should be using `%20` instead of white spaces in file names.

**Comment by SylvainCorlay** [comment]
Do you prefer to open a PR or would you prefer us to fix it?

**Comment by rs2** [comment]
I'll submit a PR

**Comment by SylvainCorlay** [comment]
Fixed in #708
