### ISSUE TITLE
bqplot in Jupyterlab  cannot display widget

### ISSUE THREAD

**Issue by dbk123** [bloomberg/bqplot#709]
I just installed bqplot using conda and enabled the extension, but when I run the example I get an error

![image](https://user-images.githubusercontent.com/16540538/44116268-137c0ae4-9fde-11e8-8ee0-ba6e36bf663e.png)

**Comment by SylvainCorlay** [comment]
Did you install the `@jupyter-widgets/jupyterlab-manager` extension as well?

**Comment by dbk123** [comment]
I reran the extension installation command and things seem to be working now.

Thanks!
