### ISSUE TITLE
ColorScale does not seem to respect min and max kwarg consistently with GridHeatMap

### ISSUE THREAD

**Issue by andymcarter** [bloomberg/bqplot#717]
The `min` and `max` parameters for ColorScale have some impact on the colors of a GridHeatMap, but it does not always respect the exact limit, allowing some values below/above threshold to be shown.

In the example below, cells 2 through 6 (counting from top left) should appear coloured, but both the 1st and 7th cells have a hue.

```python
import numpy as np
from bqplot import *

data = np.arange(1, 10).reshape([3,3])

x_sc, y_sc, col_sc = OrdinalScale(), OrdinalScale(reverse=True), ColorScale(min=2, max=6)

grid_map = GridHeatMap(color=data, scales={'column': x_sc, 'row': y_sc, 'color': col_sc})
ax_x, ax_y = Axis(scale=x_sc), Axis(scale=y_sc, orientation='vertical')

Figure(marks=[grid_map], axes=[ax_x, ax_y], padding_y=0.0)
```
![image](https://user-images.githubusercontent.com/22293319/45613851-7ad15a00-ba5f-11e8-8c67-fe9ce216e0c0.png)

However, changing only min to `min=5` gets the expected output for **both** the min and max!

![image](https://user-images.githubusercontent.com/22293319/45613898-a0f6fa00-ba5f-11e8-8dba-2f06c28c3d27.png)

Versions:
bqlot 0.10.5
ipywidgets 7.4.0

**Comment by rmenegaux** [comment]
@andymcarter the `ColorScale` extrapolates linearly from the 2 last (or 2 first) colors of the scale. In your case, as the color data gets further from the domain the color gets darker and darker until it reaches black.
We will make this more user-friendly in an upcoming PR.
