### ISSUE TITLE
Brush Interval selector is not updating selected attribute correctly

### ISSUE THREAD

**Issue by ChakriCherukuri** [bloomberg/bqplot#725]
In the latest version when I brush, the 'selected' attribute is getting updated correctly. But when I click elsewhere on the figure (thereby removing the brush selection) the selected attribute still keeps the previous value instead of setting selected to None or empty list!

@rmenegaux

**Comment by maartenbreddels** [comment]
Actually, 'selected' got replaced by selected_x and selected_y: https://github.com/bloomberg/bqplot/blob/fedc71bf75acc535ceb1785604c31a0f419d035a/bqplot/interacts.py#L412
I have a PR open here: https://github.com/bloomberg/bqplot/pull/701
But I think it should be made into a trait to also respond to observe.

**Comment by ChakriCherukuri** [comment]
@jasongrout and @maartenbreddels
the issue is on line 258 where **only** mark's selection is updated but the **selected** trait it not (when extent.length == 0). I will assign it to myself and submit a PR:)

**Comment by orpheus92** [comment]
I ran into this recently about y-axis did not get brushed correctly. Did this get fixed yet?
