### ISSUE TITLE
Single stacked bar

### ISSUE THREAD

**Issue by davidbrochart** [bloomberg/bqplot#727]
I am trying to make a single stacked bar, but it looks like I need to pad my data with zeros. Also, the colors don't work the way I expect. Am I missing something?

```python
from bqplot import OrdinalScale, LinearScale, OrdinalColorScale, Bars, Axis, Figure

x = OrdinalScale()
y = LinearScale()
col_sc = OrdinalColorScale(colors=['White', 'Blue'])

# I would like to have this:
# time = [[1, 3, 2]]
# but it gives me an empty plot
# the following works fine:
time = [
    [1, 0, 0],
    [3, 0, 0],
    [2, 0, 0]
]

# I expect to have Blue/White/Blue
# but I get White/Blue/White
busy = [1, 0, 1]

bar = Bars(x=[0], y=time, scales={'x': x, 'y': y, 'color': col_sc}, orientation='horizontal', type='stacked')
xax = Axis(scale=x, orientation='vertical')
yax = Axis(scale=y, orientation='horizontal')

bar.color = busy

Figure(marks=[bar], axes=[xax, yax])
```

![bqplot](https://user-images.githubusercontent.com/4711805/46349402-3abec980-c652-11e8-9fbe-e979aaea4056.png)

**Comment by ChakriCherukuri** [comment]
@davidbrochart you need to pass in domain to the OridinalColorScale like so:
```python
col_sc = OrdinalColorScale(domain=[0, 1], colors=['White', 'Blue'])
```

There seems to be a bug for only one stacked bar currently. Can you please file a bug report for this?

**Comment by davidbrochart** [comment]
I created PR #728 to fix this issue. It prevents squeezing `y`, which was the root cause. Not sure of all the consequences though.
