### ISSUE TITLE
LassoSelector: toggling selection off doesn't deselect marks

### ISSUE THREAD

**Issue by andymcarter** [bloomberg/bqplot#739]
From the docs I understood that toggling a selection should unselect the data, but the data remains selected after the lasso is toggled. Behaviour is correct for a *deleted* lasso, just not for a deselected lasso.

```python
import numpy as np
import bqplot.pyplot as blt
fig = blt.figure()
scatter = blt.scatter(x=np.arange(1,12), y=np.arange(1,12))
fig.marks = [scatter]
blt.lasso_selector()
blt.show()
```

bqplot 0.11.1

![2018-10-25 15 59 44](https://user-images.githubusercontent.com/22293319/47510093-52fbc000-d86f-11e8-8718-105efedea9b5.gif)

**Comment by rmenegaux** [comment]
The documentation is maybe not clear enough here: clicking a lasso selects it, which is (as of now) only used to potentially delete it. It is not meant to influence the marks.selected

**Comment by andymcarter** [comment]
Ah, I see. So no way to temporarily deactivate a selection area (and drop any contained marks from marks.selected) without deleting the lasso?
