### ISSUE TITLE
Lines.fill_opacities ignored for fill='inside'

### ISSUE THREAD

**Issue by kitizz** [bloomberg/bqplot#747]
Hi!
I noticed in [Lines.js:197](https://github.com/bloomberg/bqplot/blob/a4917aedbc8caab8b6fcb966b0ae039bd261edba/js/src/Lines.js#L197) that there is explicit logic to fill with the line opacity _only_ in the case of using `fill='inside'`. The end result is that it is then not possible to fill lines inside with transparency (ultimately leading to weirdness when trying to use interactions).

This otherwise works as expected for the other fill types. Is there a reason the logic has been implemented this way? It seems counter intuitive to me.

**Comment by SylvainCorlay** [comment]
Thanks for reporting @kitizz.

Cc @rmenegaux who might be able to fix this easily.

**Comment by rmenegaux** [comment]
@kitizz the reason it was implemented this way is that the 'inside' fill is using the built-in fill feature of the SVG path, whereas the other fill types are separate d3 area elements.

You're right in assuming `fill_opacities` should apply, all fill types should behave the same way from a user point of view. I fixed this in #752.

**Comment by kitizz** [comment]
You're awesome. Thanks!
