### ISSUE TITLE
bqplot not working on macbook

### ISSUE THREAD

**Issue by yoavfreund** [bloomberg/bqplot#83]
I followed the installation directions, but the example notebooks either stall or they don't create the 
javascript-based figure.

**Comment by SylvainCorlay** [comment]
@yoavfreund did you also perform the second stage of the installation? That is:

`python -m bqplot.install --symlink --user --force`

**Comment by yoavfreund** [comment]
Yes, I did.

It might have to do with the fact that I use both conda and pip, maybe I should uninstall bqplot and re-install it.

What are the libraries, and their versions, that I need in order for bqplot to work?

**Comment by yoavfreund** [comment]
After running pip install --update bqplot, everything works!

**Comment by SylvainCorlay** [comment]
@yoavfreund great!
The current version of bqplot depends on ipywidgets 4.1 and numpy.

**Comment by kenbabu** [comment]
I am also running through the same problem. bqplot figure is not showing but the same plots works in matplotlib.

**Comment by andymcarter** [comment]
@yoavfreund 

I had to run pip install bqplot --upgrade (not update), for anyone else finding this post looking for help with bqplot not displaying.

**Comment by dmadeka** [comment]
@yoavfreund Let us know if you found bqplot useful (or stopped using it for any reason) or whether there are any features we could use to help!
