### ISSUE TITLE
Is link_matrix a Graph adjacency matrix ?

### ISSUE THREAD

**Issue by reckoner** [bloomberg/bqplot#848]
If so, then the 

    A[i,j] = k

should mean that the `i` node has an edge with the `j` node and the weight on that edge is `k`. This is not  what is currently implemented. Seems like the existence of any `i,j` value, including `0` is enough to create an edge.

**Comment by jaredd** [comment]
@reckoner I just looked at the example Applications/Mobile Patent Suits.ipynb and it explains the link_data in a more complete manner than the docs:

```python
# for links, source and target should be indices into the nodes list
nodes_index_map = {node: i for i, node in enumerate(nodes)}
link_data = [{'source': nodes_index_map[s['source']], 
              'target': nodes_index_map[s['target']], 
              'value': s['type']} for s in suits]
```
The docs say:

> link_matrix
> link data passed as 2d matrix
> 
> Type:	numpy.ndarray of shape(len(nodes), len(nodes))

The value appears to have to map into a color scale that you pass:

```python
# encode suit type with link color
link_color_scale = OrdinalColorScale(domain=['licensing', 'suit', 'resolved'], 
                                     colors=['limegreen', 'dodgerblue', 'orangered'])
graph = Graph(node_data=node_data, link_data=link_data, link_type='arc', 
              scales={'link_color': link_color_scale}, colors=['gray'], 
              directed=True, link_distance=100, charge=-600)
```
I suspect that link_data is a more versatile way of specifying select links, as opposed to link_matrix which I imagine is better for fully-connected links with rendered lines on a continuous scale.

**Comment by reckoner** [comment]
That helps. Thanks!
