### ISSUE TITLE
Interval Selectors with date scales are not returning datetimes on the python side

### ISSUE THREAD

**Issue by ChakriCherukuri** [bloomberg/bqplot#866]
If I have an interval selector using a date scale, the 'selected' trait on the python side is returning two floats (which represent the int timestamp) instead of two date objects. 

Look at the code in the 'Fast Interval Selector' section of the Interaction Layer example notebook to highlight this issue

**Comment by martinRenou** [comment]
Apparently, it has changed since binary buffers are now used. So we send dates over the wire as floating point values. 

See https://github.com/bloomberg/bqplot/blob/master/js/src/Selector.ts#L81-L83

We should react on the `selected` change Python side, and convert floating-point values back to dates when they are received.
Problem is there is no Python equivalent of the `SelectorModel` TypeScript class. See #868

**Comment by ChakriCherukuri** [comment]
@martinRenou that's what I am doing as an interim fix. But it's too much to expect python client to convert the timestamps to dates IMHO.

**Comment by ChakriCherukuri** [comment]
@martinRenou @maartenbreddels any updates on this?

**Comment by martinRenou** [comment]
> But it's too much to expect python client to convert the timestamps to dates IMHO

We won't have another way around this, don't you think? And it doesn't cost that much, do it?

**Comment by ChakriCherukuri** [comment]
According to @maartenbreddels this is a bug. I also agree with him. Previously, 
'selected' trait returned dates but now it's returning long timestamps. Recent changes broke this.

**Comment by martinRenou** [comment]
It is a bug yes, it should be fixed. But are you saying that converting the timestamps to dates is not a fine fix?

I wanted to fix it, but I am a bit annoyed by this issue: #868. Either we do a quick and dirty fix for the dates now, or we do things correctly and first fix the other issue and then fix this one. What do you think?

**Comment by martinRenou** [comment]
I'm on it

**Comment by martinRenou** [comment]
I found the issue, the Python logic for deserializing date types is already there, it is just never called because the `date` type is not passed to Python, so Python did not know it had to deserialize. This should fix it #869

**Comment by maartenbreddels** [comment]
Awesome work @martinRenou !
