### ISSUE TITLE
0.12.0-alpha.1 - Axes do not respond to figure padding

### ISSUE THREAD

**Issue by kaiayoung** [bloomberg/bqplot#871]
The `padding_x` parameter of the `Figure` widget appears to apply padding correctly to the marks of the figure, but not the axes. See the below code to reproduce:

```
from bqplot import *
x_scale = OrdinalScale()
y_scale = LinearScale()

bar = Bars(x=list(range(10)), y=list(range(10)), scales={'x': x_scale, 'y': y_scale})
ax_x = Axis(scale=x_scale)
ax_y = Axis(scale=y_scale, orientation='vertical')

Figure(marks=[bar], axes=[ax_x, ax_y], padding_x=.1)
```

![Screen Shot 2019-06-24 at 9 49 31 AM](https://user-images.githubusercontent.com/26637211/60037423-534e9400-9666-11e9-8ef3-b67059951ede.png)

**Comment by JohanMabille** [comment]
The issue occurs with `OrdinalScale` only, if you replace `x_scale = OrdinalScale()` with `x_scale = LinearScale()`, you get the expected behavior.

**Comment by martinRenou** [comment]
I can still reproduce this issue on master. I'll check tomorrow which commit broke it again.

**Comment by martinRenou** [comment]
Yes, I can still reproduce this issue even when pointing to commit 0a11164

![issue](https://user-images.githubusercontent.com/21197331/65579591-54020980-df78-11e9-88b9-f9d049d7d079.png)

Although the result seems different, the padding does not seem to be applied correctly to the bars
