### ISSUE TITLE
Map widget's `selected` attribute is overloaded to not allow None.

### ISSUE THREAD

**Issue by SylvainCorlay** [bloomberg/bqplot#89]
At the moment, the `Map` widget overloads the `selected` attribute in order to disallow `None`.

Other marks make a distinction between an empty selection and the absence of a selection. It would be nice to unify Map with the other marks in this regard.

Note for self: this will require changing the js-side default value after #88.

cc @dmadeka

**Comment by dmadeka** [comment]
@SylvainCorlay What do you mean? In `Bars` both `None` and empty selection seem to be doing the same thing

**Comment by SylvainCorlay** [comment]
When the selection is not None, selected_style and unselected_style apply.

When the selection is None, the main style applies.

**Comment by SylvainCorlay** [comment]
An empty selection is not None...
