### ISSUE TITLE
Map widget's `color` attribute allows None

### ISSUE THREAD

**Issue by SylvainCorlay** [bloomberg/bqplot#90]
@dmadeka however, its default value is not `None`. Should it 
 - default to None
 - not allow None?

```python
color = Dict(allow_none=True).tag(sync=True, scaled=True, rtype=‘Color',                         atype='bqplot.ColorAxis’)
```

**Comment by dmadeka** [comment]
@SylvainCorlay I believe we initially made this so that the empty Dict is `None`.

The check is:

`if(!this.is_object_empty(color_data))`

**Comment by dmadeka** [comment]
Would you prefer that it be:

`if(!this.color_data)`

?

**Comment by SylvainCorlay** [comment]
Closing - discussed in person.
