### ISSUE TITLE
Grid Heat Map on_element_click broken in 0.11.6 and 0.11.7

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#901]
**Describe the bug**
Grid Heat Map on_element_click broken in 0.11.6 and 0.11.7 

**To Reproduce**
1. Install bqplot 0.11.6 or 0.11.7: `conda create -n bqplottest -c conda-forge bqplot=0.11.7`

Execute in the classic notebook:
```python

import numpy as np
from bqplot import *
from IPython.display import display

np.random.seed(0)
data = np.random.randn(10, 10)
col_sc = ColorScale()
grid_map = GridHeatMap(color=data, scales={'color': col_sc})
figure=Figure(marks=[grid_map], padding_y=0.0)

from ipywidgets import Output
out = Output()
@out.capture()
def print_event(self, target):
    print(target)
    
# test
print_event(1, 'test output')
grid_map.on_element_click(print_event)

display(figure)
display(out)
```
Click on the grid heat map.

Observe the output widget.

**Expected behavior**

The output widget shows printed output from each click. It works fine in bqplot 0.11.5.

**Environment (please complete the following information):**
- macOS 10.14.6
- FF 69

**Comment by ChakriCherukuri** [comment]
closing this as my PR has been merged into 0.11.x
