### ISSUE TITLE
GridHeatMap does not add/remove rows or columns when new data is assigned

### ISSUE THREAD

**Issue by kaiayoung** [bloomberg/bqplot#913]
When assigning a new matrix to the `color` parameter, the grid is not reshaped to conform to the new data:

```
import numpy as np
from bqplot import *
grid_map = GridHeatMap(color=np.random.randn(5, 5),
                       scales={'color': ColorScale()})
Figure(marks=[grid_map])
```

Run the below in a new cell, and you can observe that no new rows or columns are created, though the values are updated for the visible ones:

`grid_map.color = np.random.randn(10, 10)`

**Comment by martinRenou** [comment]
The number of rows and columns seems to be set at the creation of the widget:

```python
def __init__(self, **kwargs):
    data = kwargs['color']
    kwargs.setdefault('row', range(data.shape[0]))
    kwargs.setdefault('column', range(data.shape[1]))
    [...]
```

And it never changes again. What do you think would be the best way to fix this? Maybe `row` and `column` attributes should have a default value of `None`, and when it is `None` the front-end display the entire grid it receives?
