### ISSUE TITLE
Rare issue: mark_views.views undefined when using WebGL marks

### ISSUE THREAD

**Issue by maartenbreddels** [bloomberg/bqplot#924]
This sometimes happens when a webgl mark is used:
```
Figure.js:839 Uncaught TypeError: Cannot read property 'views' of undefined
    at e.Figure.render_gl (Figure.js:839)
    at e.Figure._update_gl (Figure.js:833)
    at Figure.js:829
```

Which means `this.mark_views.views` is undefined. This may be a timing issue with promises.

**Comment by martinRenou** [comment]
I don't quite get it, there seem to be a condition checking for the undefined value of `this.mark_views`

```javascript
render_gl() {
    if(this.mark_views === undefined)
        this.update_gl() // we got call to soon, maybe next frame?
    return Promise.all(this.mark_views.views).then((views) => {
        [...]
    });
}
```

How could `mark_views` be undefined?

**Comment by martinRenou** [comment]
Oh, actually this code is wrong.

Calling `update_gl` under does nothing... Because `_update_requested` is true and `update_gl` does:

```javascript
update_gl() {
    if(!this._update_requested) {
       this._update_requested = true
       requestAnimationFrame(() => this._update_gl())
   }
}
```

Will fix it

**Comment by maartenbreddels** [comment]
Wait, I don't understand. I think we need to return after this.update_gl(), but I don't understand 'under does nothing'?

**Comment by martinRenou** [comment]
> I don't understand 'under does nothing'?

I edited my message, there is no "under" anymore.

Yes, actually `render_gl` needs to return a Promise. So we need to do smth like:
```javascript
if(this.mark_views === undefined) {
    return Promise.resolve().then(() => {
        this.update_gl();
    });
}
```

Also, `update_gl` does nothing because `_update_requested` is true at this point. So we need to reset `_update_requested` to false

**Comment by maartenbreddels** [comment]
I see. I think we don't need to return a promise, can we do... ?
```javascript

    update_gl() {
        if(!this._update_requested) {
           this._update_requested = true
           requestAnimationFrame(() => this.render_gl())
       }
    }

    render_gl() {
        if(this.mark_views === undefined) {
            requestAnimationFrame(() => this.render_gl()) // we got call to soon, maybe next frame?
        }
        return Promise.all(this.mark_views.views).then((views) => {
            // render all marks that have a render_gl method
            this.renderer.autoClear = false;
            this.renderer.autoClearColor = new (THREE.Color as (x) => void)(0x000000);
            this.renderer.clear()
            let marks_gl = _.filter(views, (view: any) => view.render_gl)
            _.each(marks_gl, (mark: any) => {
                mark.render_gl()
            })
            this._update_requested = false;
        });
```

**Comment by martinRenou** [comment]
> I think we don't need to return a promise

We do.

In the `get_svg`  method we do something like `return this.render_gl().then(() => {`

**Comment by maartenbreddels** [comment]
you're right, good catch.
