### ISSUE TITLE
ColorScale not working with jupyter_sphinx

### ISSUE THREAD

**Issue by kaiayoung** [bloomberg/bqplot#926]
When using `ColorScale` with `jupyter-sphinx`, it appears that the DOM elements are not being updated with the correct colors, and are instead solid black. This seems to be the case with many marks, but is particularly relevant with the `GridHeatMap` and `Scatter` marks. See the below code, and screenshot of modified bqplot docs:

```
from bqplot import *
sc_x = LinearScale()
sc_y = LinearScale()
sc_c1 = ColorScale()
scatter = Scatter(x=[1,2,3,4,5],
					y=[2,4,3,1,5],
					color=[1,2,3,4,5],
					default_size=200,
					scales={'x': sc_x,
							'y': sc_y,
							'color': sc_c1})
Figure(marks=[scatter])
```
![Screen Shot 2019-09-25 at 3 13 49 PM](https://user-images.githubusercontent.com/26637211/65643959-d2c26b00-dfa7-11e9-81ab-88da77f579fe.png)

**Comment by martinRenou** [comment]
As you suspected, this is fixed by for the marks color #929

![fix](https://user-images.githubusercontent.com/21197331/65880332-e9930400-e391-11e9-872b-a97a72002d54.png)


Although this small blue dot is weird... Looking at the DOM structure it seems to come from a Legenb area

**Comment by ibdafna** [comment]
This should be solved now, I believe.

**Comment by ibdafna** [comment]
Closing as I think #980 and #983 fix this, but we can always reopen if it's another issue.

Thanks!
