### ISSUE TITLE
Modify ts and css

### ISSUE THREAD

**Issue by Dadatata-JZ** [bloomberg/bqplot#947]
I am new to bqplot. According to the introduction, I should be able to modify the TS and CSS in real-time. What should I do after modifying these files? I was saving the code and run 

$ jupyter nbextension install --py --symlink --sys-prefix bqplot
$ jupyter nbextension enable --py --sys-prefix bqplot

And open jupyter notebook under "example" folder. The code didn't affect. Any tutorials for these? I am in MacOS

Thanks

**Comment by martinRenou** [comment]
Once you installed the project with those commands, no need to run them again. If you change the TS or CSS code you just need to:
- run `npm run build` from the `js` directory
- hard refresh your notebook page

And you should see the changes

**Comment by Dadatata-JZ** [comment]
After running npm run build, the modification is overwritten from JS files. However, the modification for CSS file can not be addressed. 

More specific, 
```
.bqplot > svg .lassoselector path {
  fill: none;
  stroke: orange;
  stroke-width: `4`
}
```
I changed stroke-width to "1" but after running `npm run build`, it automatically turned back to 4.
