### ISSUE TITLE
How the python classes link to js components internally

### ISSUE THREAD

**Issue by Dadatata-JZ** [bloomberg/bqplot#948]
I am trying to make some js/ts components as additional functions. However, I am curious how the js finally links to python. Do they have to be named exactly the same? And is this what jupyter-extension actually does?

Thanks

**Comment by martinRenou** [comment]
Only the `model_name` and the `view_name` are important, then it's up to `ipywidgets` to link the Python model to the JavaScript model

**Comment by Dadatata-JZ** [comment]
I realize on the git, there are no js files anymore, only ts? are they same things right now? regarding the ipywidgets will link python and ts instead of js now.

**Comment by martinRenou** [comment]
Yes, it's the same :)
