### ISSUE TITLE
Assigning the side attribute for the axis is not reliable

### ISSUE THREAD

**Issue by DougRzz** [bloomberg/bqplot#956]
**To Reproduce**
```python
import bqplot as bq
axis = bq.Axis(scale = bq.LinearScale() ) 
axis.orientation = 'vertical'
axis.side = 'right'
```
But ```axis.side != 'right'``` unless ```axis.side ='right'``` is executed in another cell.

**Expected behavior**
axis.side == 'right'

**Screenshots**
![image](https://user-images.githubusercontent.com/3510318/67559868-ae29f200-f711-11e9-856d-1023cf1dd4a8.png)

**Environment (please complete the following information):**
 - Operating System and Version: Windows 10
 - Browser [e.g. Firefox, Safari] (if applicable): Chrome

**Suggestion:**
Remove the orientation attribute and only have the side attribute.  Orientation is superfluous if side is specified as either top, bottom, left or right.

**Comment by martinRenou** [comment]
I agree with the fact that `orientation` is redundant. Maybe this could be removed in a backwards incompatible release.

**Comment by martinRenou** [comment]
Would you mind reopening this @SylvainCorlay ?
