### ISSUE TITLE
Need help coloring histogram by each bins

### ISSUE THREAD

**Issue by RichardoTiono** [bloomberg/bqplot#965]
Hello,

I just recently stumbled upon this great library. But I have been having problem giving color the my histogram. I want to color it based on hsv colorspace and each bin would have different color. I managed to do this with matplotlib but since I plan to have some gui interaction with it, I tried to convert it to bqplot. Sadly on bqplot, don't know why even when I specified multiple color on the parameter and the histogram identifies it (I print the plt.hist), it only shows the first color in it which is weird
This is the code I used for matplotlib

> image = np.float32(ori_image)
> image = cv2.cvtColor(ori_image,cv2.COLOR_BGR2HSV_FULL)
> hues=image[:,:,0]/255*360
> #get hue channel only
> #create bin interval (0,1),(1,2),...
> binEdges = np.arange(0,361)
> row,col=hues.shape
> hues= hues.reshape(row*col) 
> #assign each value to corresponding bins
> #hist=np.bincount(np.searchsorted(binEdges,hues),minlength=361)[1:]
> #print(hist)
> rainbow = plt.get_cmap('hsv')
> fig = plt.figure()
> fig.set_size_inches(18.5, 10.5, forward=True)
> N, bins, patches=plt.hist(x=hues,bins=binEdges)
> #apply hsv color for each bin
> for i in range(len(patches)):
>     patches[i].set_facecolor(rainbow(i/len(patches)))
> plt.show()

This is the result of the code above
[Click me](https://imgur.com/a/tuaQwe5)

this is the printout of the plt.hist

> Hist(colors=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']

which output only blue color that is #1f77b4

Please help me resolve this issue

**Comment by martinRenou** [comment]
I guess this is a bug. I will look into it. Sorry for the late reply.

**Comment by martinRenou** [comment]
Please correct me if I am wrong, but I fill like you could use the `Bar` instead of `Hist` in your case :) You would have the colors working until `Hist` is fixed.

**Comment by martinRenou** [comment]
I am opening another issue which lists all the `Hist` issues that I found #995. I suppose we can close this one and follow up on the other issue.

**Comment by martinRenou** [comment]
This issue is now fixed. It should be closed

**Comment by martinRenou** [comment]
@ibdafna
