### ISSUE TITLE
Display Selective Labels in the bqplot 

### ISSUE THREAD

**Issue by saurabhheda** [bloomberg/bqplot#977]
Hi, 
I was plotting a pie chart and would like to have only selected labels to be displayed in the pie chart. For example there is display_labels attribute in the Pie function but values for this is the [none, outside or inside]. 

I only want selective labels (for example maximum of the pie and minimum of the pie)

**Comment by martinRenou** [comment]
Sorry for the late reply.

You can dynamically update labels under selection, for example this works just like you explained

```python
from bqplot import Pie, Figure
import numpy as np
import string

letters = list(string.ascii_uppercase)

data = np.random.rand(3)
pie = Pie(sizes=np.random.rand(10), display_labels='outside', labels=letters)

pie.selected_style = {'opacity': 1, 'stroke': 'white', 'stroke-width': 2}
pie.unselected_style = {'opacity': 0.2}
pie.interactions = {'click': 'select'}

def update_labels(change):
    selected_indices = change['new']
    pie.labels = [letter if idx in selected_indices else '' for idx, letter in enumerate(letters)]

pie.observe(update_labels, 'selected')

fig = Figure(marks=[pie], animation_duration=1000)
fig
```

**Comment by saurabhheda** [comment]
@martinRenou Thanks for your response and quite useful. In my case if I display the labels at first point (display_labels=outside) as you illustrated in your code my graph will look too messy as shown below. 

![image](https://user-images.githubusercontent.com/2179996/72585580-a646ac00-3914-11ea-83e1-cd76a833ee7f.png)

I want to show only two labels in my pie chart (maximum pie label and minimum pie label) or nothing initially but when I click a pie I see its label.

**Comment by martinRenou** [comment]
So, again, you can easily do it programmatically :)

Something like:
```python
from bqplot import Pie, Figure
import numpy as np
import string

letters = list(string.ascii_uppercase)

data = np.random.rand(26)

pie = Pie(sizes=data, display_labels='outside', labels=letters)
fig = Figure(marks=[pie], animation_duration=1000)

def update_labels(*args):
    min_idx = np.argmin(pie.sizes)
    max_idx = np.argmax(pie.sizes)

    pie.labels = [letter if idx in [min_idx, max_idx] else '' for idx, letter in enumerate(letters)]

update_labels()

# Observe sizes update
pie.observe(update_labels, 'sizes')

fig
```

And because we observe `sizes` update, you can update it dynamically, it will recompute the labels automatically:
![pie](https://user-images.githubusercontent.com/21197331/72593760-18fc5b00-3906-11ea-9d53-5e4fc22b9014.gif)


(Note that I am using the master branch so you might not get the same visual result)

**Comment by saurabhheda** [comment]
@martinRenou  Awesome, Thanks a lot. That is what I was looking for. I need to see how I can pass on and use this in my function that is generating Pie graph. Again Thanks

**Comment by saurabhheda** [comment]
@martinRenou  Also what if I would like to maintain labels for all the pies in the tooltip because while I used this code it is not showing any label in the tooltip for other pies (except max and min) 

for example as below in the image where no labels in the tool for other pies

![image](https://user-images.githubusercontent.com/2179996/72601060-b2456480-393a-11ea-92ac-6302971cb9e0.png)

**Comment by martinRenou** [comment]
Mmmh this is tricky... I cannot make it work with the tooltip, but you can do the following:

```python
from bqplot import Pie, Figure, Tooltip
import numpy as np
import string

letters = list(string.ascii_uppercase)

data = np.random.rand(26)

pie = Pie(sizes=data, display_labels='outside', labels=letters)
fig = Figure(marks=[pie], animation_duration=1000)

def update_labels(*args):
    min_idx = np.argmin(pie.sizes)
    max_idx = np.argmax(pie.sizes)

    pie.labels = [letter if idx in [min_idx, max_idx] else '' for idx, letter in enumerate(letters)]

update_labels()

# Observe sizes update
pie.observe(update_labels, 'sizes')

# Display the size value next to the label:
pie.display_values = True

# On hover event, update the labels
def on_hover(widget, event):
    hover_idx = event['data']['index']

    min_idx = np.argmin(pie.sizes)
    max_idx = np.argmax(pie.sizes)

    new_labels = [letter if idx in [min_idx, max_idx] else '' for idx, letter in enumerate(letters)]
    new_labels[hover_idx] = letters[hover_idx]

    pie.labels = new_labels

pie.on_hover(on_hover)

fig
```
![hover](https://user-images.githubusercontent.com/21197331/72604295-e872ec00-391a-11ea-8130-34a4ff50d61d.gif)

**Comment by martinRenou** [comment]
(IMO, this looks better than the tooltip anyway :P)

**Comment by saurabhheda** [comment]
@martinRenou  Looks awesome Interesting, Thank you so much.

**Comment by martinRenou** [comment]
Sure! Would you mind closing this issue? Don't hesitate to ask more questions

**Comment by saurabhheda** [comment]
@martinRenou Hi Martin, While I was executing your code I found out that values are also displayed with pie.display_values=True as shown below. 

![image](https://user-images.githubusercontent.com/2179996/72661879-b1c5d000-3a05-11ea-960a-236cbf74db6b.png)

**Comment by martinRenou** [comment]
Oh yes... I realized that was an issue on previous versions.

I made a fix for that here: https://github.com/bloomberg/bqplot/pull/1008

Hopefully, this will be included in the next release.

**Comment by saurabhheda** [comment]
@martinRenou  Is there any quick workaround which I can do at this moment to fix this or when can we expect latest release, sorry too many questions.

**Comment by martinRenou** [comment]
No worries! Hopefully, we will release `0.12.3` this week with the mentioned PR in, but I cannot promise anything.

A workaround for you would be to display the value in the label yourself. Which means:
- set `display_values` to `False`
- set `pie.labels` to `['{}: {}'.format(letter, pie.sizes[idx]) if idx in [min_idx, max_idx] else '' for idx, letter in enumerate(letters)]`

**Comment by saurabhheda** [comment]
Hi @martinRenou 
Is this not even fixed in 0.12.6 now? Because I re-installed bqplot and again the same error.

**Comment by martinRenou** [comment]
I see it working on the latest release. How did you install bqplot? Are you using Jupyter Notebook or Jupyter Lab?

**Comment by saurabhheda** [comment]
I am using jupyter notebook and installed bqplot using pip install bqplot.

With pip freeze I see the version of bqplot as 0.12.6

**Comment by martinRenou** [comment]
Could you try running:
```
jupyter nbextension install --overwrite --py --sys-prefix bqplot
```

**Comment by martinRenou** [comment]
and refresh your Jupyter Notebook page

**Comment by saurabhheda** [comment]
Not sure it still shows the below output. 
![image](https://user-images.githubusercontent.com/2179996/78998869-21f87380-7b67-11ea-87aa-66a783841b1c.png)

**Comment by martinRenou** [comment]
Could you show me the output of `jupyter nbextension list`?

**Comment by saurabhheda** [comment]
I see the below output on command line

Known nbextensions:
  config dir: C:\Users\SAURABH.HEDA\.jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
  config dir: c:\users\saurabh.heda\appdata\local\programs\python\python36-32\etc\jupyter\nbconfig
    notebook section
      bqplot/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok

**Comment by martinRenou** [comment]
I suggest you try again from a clean environment, always a good idea

**Comment by saurabhheda** [comment]
It is working now. Thanks

**Comment by saurabhheda** [comment]
@martinRenou Sorry one more question, Is it possible to have a different layer for the labels as it is in the tooltip?
I have big labels and they are not fitting all the way in the given area hence wondering if something like this possible

**Comment by martinRenou** [comment]
Not sure it's possible. Did you try putting a newline in your label `\n`? Not sure that would work. You could still increase the drawing area though, through the layout attribute: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html

```python
figure.layout.width = '800px'
figure.layout.height = '800px'
```
