### ISSUE TITLE
ColorAxis random position in Firefox

### ISSUE THREAD

**Issue by davidbrochart** [bloomberg/bqplot#981]
**Describe the bug**
The `ColorAxis` sometimes appears in the middle of the figure in Firefox.

**To Reproduce**
1. `jupyter notebook bqplot/examples/Scales/Color\ Scales.ipynb`
2. Execute cells 1 and 2.
3. Execute cell 2 again until you see the `ColorAxis` appear in the middle of the figure.

**Expected behavior**
In Chromium, the `ColorAxis` always appears on the right side, as expected.

**Screenshots**
![img](https://user-images.githubusercontent.com/4711805/70133687-e4e71680-1686-11ea-856c-3abad1a03cb6.png)

**Environment (please complete the following information):**
 - Ubuntu Linux 19.10
 - Browser (if applicable): Firefox

**Comment by martinRenou** [comment]
This is super weird, it should have been fixed by https://github.com/bloomberg/bqplot/pull/964. I am wondering if you are executing the right JavaScript on the page..

**Comment by martinRenou** [comment]
https://github.com/bloomberg/bqplot/pull/982 Should definitely fix this, as we get rid of this hardcoded size.

**Comment by davidbrochart** [comment]
Indeed, #982 seems to fix it. Thanks!
