### ISSUE TITLE
pie chart: display bug when changing sizes property

### ISSUE THREAD

**Issue by pierredittgen** [bloomberg/bqplot#991]
**Describe the bug**
Updating `sizes` property of existing pie chart causes display bugs.

**To Reproduce**
- Copy-paste this code in a notebook:
```python
import bqplot
import ipywidgets as ipyw
import numpy as np

DATA = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
DEFAULT_LENGTH = 4

# pie chart
pie = bqplot.marks.Pie(sizes=np.array(DATA[:DEFAULT_LENGTH]))
pie_fig = bqplot.Figure(marks=[pie], title="simple pie", animation_duration=300)

# slider
def on_length_change(x):
    global DATA
    index = x.new
    with pie.hold_sync():
        pie.sizes = np.array(DATA[:index])
select_opts = [(v, v) for v in range(1, 11)]
select_widget = ipyw.SelectionSlider(options=select_opts, value=DEFAULT_LENGTH,
                                     description="Data length", style={'description_width': 'initial'})
select_widget.observe(on_length_change, type='change', names='value')

ipyw.VBox([select_widget, pie_fig])
```
- move slider to the right to increase data length

**Expected behavior**
Pie chart display may adapt to new `sizes` values

**Screenshots**
![image](https://user-images.githubusercontent.com/14194768/70726445-5fa2d800-1cfe-11ea-96f5-ca87079713e6.png)
Initial state

![image](https://user-images.githubusercontent.com/14194768/70726545-89f49580-1cfe-11ea-8488-b136f30d217a.png)
Increasing data length cause an empty part to appear in the pie chart

**Environment (please complete the following information):**
- Operating System and Version: Debian Linux 10.2 "buster" 64bits
- Browser [e.g. Firefox, Safari] (if applicable): Firefox Quantum 68.2.0esr
- Python version 3.7.3
- Virtual env:
```bash
pip install -r requirements.txt
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install bqplot --no-build
jupyter labextension install jupyter-leaflet --no-build
jupyter labextension install @jupyter-voila/jupyterlab-preview --no-build
jupyter lab build
```
- requirements.txt
```
bqplot==0.12.1
ipyleaflet==0.11.6
ipywidgets==7.5.1
jupyterlab==1.2.3
palettable==3.3.0
pandas==0.25.3
requests==2.22.0
voila==0.1.20
```
**Additional context**
Display bug doesn't occur when data lengh decreases.

**Comment by martinRenou** [comment]
Thanks a lot for those really well-written issues. I'll try to fix this one.

**Comment by pierredittgen** [comment]
Thanks! Tell me if you need more info to investigate.

**Comment by martinRenou** [comment]
This is now fixed, it can be closed

**Comment by martinRenou** [comment]
@ibdafna
